### ISSUE TITLE
Relative URLs

### ISSUE THREAD

**Issue by davidhellmann** [sebastian-lenz/craft-linkfield#10]
Can you switch the URL Field type to text that we can use stuff like `/contact/` or maybe add a custom option?

**Comment by sebastian-lenz** [comment]
I'll add an option to disable the validation of input elements.

**Comment by davidhellmann** [comment]
Danke! :)

**Comment by sebastian-lenz** [comment]
Gern' geschehen 😉 

I've added this feature in v1.0.4 so I'll close this issue for now. If there are any problems remaining, please let me now!
