### ISSUE TITLE
Entry title can wrap out of editor pane

### ISSUE THREAD

**Issue by wihodges** [sebastian-lenz/craft-linkfield#100]
If entry is selected with a super long title it wraps off the editor pane. Not critical but should probably just cut off at some point. See example below:

<img width="1016" alt="Screenshot 2020-04-16 16 27 51" src="https://user-images.githubusercontent.com/286956/79508467-3d4bfe80-7fff-11ea-82f0-f5d84cbf19f8.png">

**Comment by sebastian-lenz** [comment]
Okay, I've changed the fields stylesheet, it uses a flex box now that cuts of the element title if it becomes too long.
