### ISSUE TITLE
getLink() and getText() do not output the link text when using the Telephone link type

### ISSUE THREAD

**Issue by jrrdnx** [sebastian-lenz/craft-linkfield#101]
When using the Telephone link type and rendering the link either with `getLink()` or manually outputting the properties and using `getText()`, nothing is displayed.

The href portion works fine using both `getLink()` and `getUrl()`.

Using version 1.0.21

**Comment by sebastian-lenz** [comment]
I've just tested this and it works as expected. All text based links (urls, phone, mail, etc.) do not return a default text. You must either:
- specify a default text in the field settings
- enter a custom text with the link
- pass the desired text to the `getLink` method

**Comment by jrrdnx** [comment]
@sebastian-lenz I would expect this to return the link itself if no custom text is entered.

For instance with the phone link type there's no way for me to get just the phone number itself (without the "tel:" prefixed) without also running a string replace to strip that off.

I feel it would be a better user experience for the `getText()` method to return the supplied link as a fallback if there is no custom text, otherwise users would be required to enter the phone number/email address/URL/etc. twice for each link.

**Comment by sebastian-lenz** [comment]
You can get the pure value of the link using the attribute `value`. To get the behavior you are looking for you can do something like this in templates:

```
{{ myLinkField.link(myLinkField.text|default(myLinkField.value)) }}
```

I understand your motivation behind this issue, but I see no easy way to implement this change without breaking the field behavior for people that use the field the way it is.

**Comment by jrrdnx** [comment]
Perfect, thank you!
