### ISSUE TITLE
Get the Link Type?

### ISSUE THREAD

**Issue by wihodges** [sebastian-lenz/craft-linkfield#103]
Might be overlooking the documentation, but I don't see a way to see what the link type selection is? E.G. Entry, Url, Custom ... etc.  It would be nice to be able to query the type of link and then do different things based upon that value. 

{{ item.myLinkField.getType() }}

![Screen Shot 2020-05-27 at 9 50 38 PM](https://user-images.githubusercontent.com/286956/83093005-400d2b00-a064-11ea-9904-52ffc42fcde1.png)

**Comment by sebastian-lenz** [comment]
Hi! You can access the link type using the attribute `type`. So you where pretty near in your example:

```
{{ item.myLinkField.type }}
```
