### ISSUE TITLE
Integrity constraint violation when migrating existing project to 2.0.0-beta.8

### ISSUE THREAD

**Issue by holmey** [sebastian-lenz/craft-linkfield#105]
When running the migrating on one of our existing Projects (linkfield from Version 1.0.21 to 2.0.0-beta.8) MySQL throws an "Integrity constraint violation" Error.

`Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails`

When searching for the reason of this issue we found some linkfield entry-references in our database pointing to entries that do not exist (anymore). I do not know if this is an expected behavior or if this inconsistency is caused by any other problem.

The new constraint needs this referenced entry to exist and causes the error when updating the database.

`CONSTRAINT 'craft_lenz_linkfield_linkedId_fk' FOREIGN KEY ('linkedId') REFERENCES 'craft_elements' ('id') ON DELETE SET NULL ON UPDATE SET NULL`

I could locally fix this issue in the migration file by checking if the entry exists before the ´batchInsert´ in the ´updateLinkField´ method.

```php
...
unset($payload['type']);
unset($payload['value']);

$doesExist = true;
if($value && is_numeric($value)) {
    $doesExist = (new Query())
        ->select('id')
        ->where(['id'=> $value])
        ->from('{{%elements}}')
        ->exists();
}

if($doesExist) {
    $insertRows[] = [
        $row['elementId'],                          // elementId
        $row['siteId'],                             // siteId
        $field->id,                                 // fieldId
        is_numeric($value) ? intval($value) : null,         // linkedId
        is_numeric($value) ? $row['siteId'] : null, // linkedSiteId
        $type,                                      // type
        is_numeric($value) ? null : $value,         // linkedUrl
        Json::encode($payload)                      // payload
    ];

}

$this->batchInsert(LinkRecord::tableName(), [
    'elementId', 'siteId', 'fieldId', 'linkedId', 'linkedSiteId', 'type', 'linkedUrl', 'payload'
], $insertRows);
...
```

**Comment by sebastian-lenz** [comment]
Hi, thanks for reporting this. Version 2 of the link field stores links in a dedicated table and referred elements now are actual database relations. Looks like your data contains links to deleted elements which the old version just ignored upon loading the links.

I'll just copy over your proposed change with a slight modification, instead of skipping the record altogether I would set the element id to `NULL`.

**Comment by sebastian-lenz** [comment]
Forgot to tag the commit, the fix lives here:
https://github.com/sebastian-lenz/craft-linkfield/commit/796c7174cec401a64526c68778ae99a53a342876

**Comment by sebastian-lenz** [comment]
If you'd like to feel free to open a pull request (e.g. create `CONTRIBUTORS.md`) so your contribution is credited 😄

**Comment by sebastian-lenz** [comment]
Okay, I've just release 2.0.0-beta.9 containing this fix. 

Thank you for your help!
