### ISSUE TITLE
enableAllLinkTypes is alway true when migrating existing project to 2.0.0-beta.8

### ISSUE THREAD

**Issue by holmey** [sebastian-lenz/craft-linkfield#106]
Entries with specific link types do not implement the setting `enableAllLinkTypes` in our existing database and when migrating them they will not have this setting either.

The LinkField field in 2.0.0-beta.8 has a public variable `enableAllLinkTypes` thats true by default. When these Fieldsettings get serialized by `normalizeValue` in `ForeignField` this variable does not get overridden since it does not exist in the serialized settings.
This causes the toggle switch in the CMS to be always active for migrated fields with specific link types.

I could locally fix this issue by setting the variable `enableAllLinkTypes` to false by default when migrating. Maybe it is a better idea to solve this issue in the LinkField Class to keep the footprint of the settings in the database small.

```php
...
$settings['enableAllLinkTypes'] = false;

if (isset($settings['allowedLinkNames'])) {
    $allowedLinkNames = $settings['allowedLinkNames'];
    if (!is_array($allowedLinkNames)) {
        $allowedLinkNames = [$allowedLinkNames];
    }

    foreach ($allowedLinkNames as $linkName) {
        if ($linkName == '*') {
            $settings['enableAllLinkTypes'] = true;
        } else {
            $settings['typeSettings'][$linkName]['enabled'] = true;
        }
    }
}
...
```

**Comment by sebastian-lenz** [comment]
Sounds like you had a rough time upgrading the plugin, I'm sorry for that. You are completely right, and this is a bug.

Would you like to submit the change as a pull request so your contribution shows up? Otherwise I would add the change.

**Comment by holmey** [comment]
Thank you for the fast response. This plugin is free, so I am happy to help.
I submitted a pull request for this issue.
Are there any plans for the release of this Version?

**Comment by sebastian-lenz** [comment]
Great, thank you for the PR! I'll issue a new version after I've checked on the other issue that popped up yesterday. If you want to switch to this version early you may set the version requirement in your composer.json to `v2.0.x-dev`.

**Comment by sebastian-lenz** [comment]
Okay, I've just release 2.0.0-beta.9 containing this fix. 

Thank you for your help!
