### ISSUE TITLE
Custom query not saving when enabled on multiple element types

### ISSUE THREAD

**Issue by benface** [sebastian-lenz/craft-linkfield#108]
### Steps to reproduce

1. Create a Link field and check "Allow users to enter custom queries that will be appended to the url" for both "Entry" and "User" element types.
2. Add the field to some field layout and go edit that entry/whatever.
3. In the field, select an entry and add a custom query. Save.
4. Notice the custom query wasn't saved!
5. Go back to editing the entry and now select a user in the field, and add a custom query. Save again.
6. Notice this time it was saved. The custom query seems to be saved only for the last element type for which it is enabled (starting from the top of the list).

### Info

- Craft version: 3.4.22.1
- Plugin version: 1.0.22

**Comment by sebastian-lenz** [comment]
Hi, thanks for reporting this. I Can confirm that this does currently not work as intended.
