### ISSUE TITLE
URLs aren't validated

### ISSUE THREAD

**Issue by darylknight** [sebastian-lenz/craft-linkfield#109]
When you use a URL field in Craft, the client has to type the protocol (https://). When External URL is selected in Typed Link Field, it looks like this doesn't happen. I've just done a broken link report on a client site, and one of the fields is this:

![image](https://user-images.githubusercontent.com/1250017/84664424-340bdf00-af27-11ea-8743-9f0054f04874.png)

Which means the front end code is outputting https://theclientwebsite.com/www.duttongoldfield.com

**Comment by darylknight** [comment]
Hmm, having literally just tested this after filing the issue, I tried putting random text in there, and it DID get validated. Then I changed it back to `www.duttongoldfield.com`, and it looks like Typed Link field changed the URL to http://www.duttongoldfield.com.

What would cause it to automatically fix the URL when I enter it, but not when the client does? I think it'd be more reliable if it just failed a URL that didn't include a protocol.

**Comment by sebastian-lenz** [comment]
I did a quick test and I do not see the issue. The url input passes the url to the url validator included in Craft ([here](https://github.com/sebastian-lenz/craft-linkfield/blob/master/src/models/InputLinkType.php#L259) or [here](https://github.com/sebastian-lenz/craft-linkfield/blob/v2.0/src/models/input/InputLink.php#L114)) which [checks for a schema](https://github.com/yiisoft/yii2/blob/master/framework/validators/UrlValidator.php#L92). So as long as you do not disable the validation on the field, this should not pass.

The validator actually include the code to prepend a default schema, but the plugin never activates this behavior and we do not alter the url before saving it. So I have no explanation for the what you are seeing.

It's a bit strange that the link type is called "External URL". Is this a different url field?

**Comment by darylknight** [comment]
Argh I'm being an idiot. I started using Typed Link Field for all sites a year ago or so, and this site was made before that, so it's using LinkIt still. Sorry for wasting your time!
