### ISSUE TITLE
[v2.0.x-dev]: URL field setting doesn't save.

### ISSUE THREAD

**Issue by timkelty** [sebastian-lenz/craft-linkfield#110]
With **Input fields: Url** selected in the field settings, the setting does not save. It seems this only happens when Url is the only "input field" selected.

<img width="530" alt="Screen Shot 2020-07-02 at 2 10 39 PM" src="https://user-images.githubusercontent.com/18329/86395181-d3daa400-bc6d-11ea-9c42-e2a4baf3cd3a.png">

**Comment by sebastian-lenz** [comment]
This is a bug in Craft CMS core, please see
https://github.com/craftcms/cms/issues/6320
