### ISSUE TITLE
Setting not saving on 1.0.23

### ISSUE THREAD

**Issue by darylknight** [sebastian-lenz/craft-linkfield#111]
I've just tried to untick the below option from this field inside a Matrix field, and when I save the field, it goes back to being ticked.

![image](https://user-images.githubusercontent.com/1250017/86475606-ad8c3580-bd4d-11ea-9bc9-9dd10dff046a.png)

Let me know what other info I can give you!

Craft Pro 3.4.26
Typed Link Field 1.0.23

**Comment by sebastian-lenz** [comment]
This is a bug in Craft CMS core, please see
https://github.com/craftcms/cms/issues/6320
