### ISSUE TITLE
Add the ability to know the URL / Link Type

### ISSUE THREAD

**Issue by michtio** [sebastian-lenz/craft-linkfield#112]
Now currently we can use several options to create our links.

- Assets
- Categories
- Sites
- Entries
- URL 
- Custom
- Mail
- Telephone

--> Which is nice, but for example I would like to have the option to do something like 

`entry.linkTypeField.type` which will display the actual link type, so if it's a link to assets, I would want it to parse "asset", link to mail "mail".

This would make it possible to create a single linkField eg. as an image source, that image could link to an internal entry or external url, for the sake of UX external links could then be designed a little different, or custom icons like an external link icon could be added based on the type.

Same goes for mail or telephone, etc ...

**Comment by sebastian-lenz** [comment]
Hi @michtio! Actually what you are proposing here should work right out of the box, link fields carry an attribute called `type` which specifies the selected link type. I have to admit that we did not document the available attributes well as noted in #96 so we are aware that problem.
