### ISSUE TITLE
Cannot get full link object using GraphQL in Craft 3.5

### ISSUE THREAD

**Issue by howells** [sebastian-lenz/craft-linkfield#115]
I was fairly sure this worked before, but I can't seem to get the full link object using GraphQL - the field is only a string, so I can't get a sub-selection when I want to grab the url and label, returning the error `"Field \"secondaryActionLink\" of type \"String\" must not have a sub selection."`

**Comment by sebastian-lenz** [comment]
Hi @howells, are you using version 2 of the plugin? With version2 you should get access to those sub fields on the official GraphQL support in Craft.

**Comment by howells** [comment]
Ah no I'm using the version that's available in the plugin store, 1.0.23 - I hadn't realised there was a version 2. I've just upgraded and seems to work!

**Comment by sebastian-lenz** [comment]
I've added support for the official GraphQL API in the v2 branch, v1 of the plugin supports the old third party GraphQL plugin. I hope we can soon switch to v2 of the plugin. It is safe to use it, I actually use v2 in all of my projects. I primarily did not pull the trigger as the update path is quite complex and I still need to test it, the plugin itself is pretty stable.

I'll close this issue for now. If you encounter any other problems, please feel free to open a new issue.
