### ISSUE TITLE
Commerce Exceptions

### ISSUE THREAD

**Issue by spAnser** [sebastian-lenz/craft-linkfield#117]
I think this applies to both v1 and v2 but if you have craft commerce installed through composer but not installed in craft. The plugin starts throwing exceptions because it tries to pull in commerce things but it isn't available. Might need to tweak the detection of commerce being present.

**Comment by sebastian-lenz** [comment]
Hi, @spAnser, thank you for reporting this.

**Comment by sebastian-lenz** [comment]
We now additionally check whether the commerce plugin is actually enabled before trying to interact with it.
