### ISSUE TITLE
Entry link type missing "+ Choose" button when used in asset field layout in modal view

### ISSUE THREAD

**Issue by TheFunkyMonk** [sebastian-lenz/craft-linkfield#118]
## Description

When assigning a Link field to the field layout of an asset volume, the "+ Choose" button is missing from the Entry link type when the asset fields are viewed in the modal-style display.

## Steps to reproduce

1. Create a Link field type with Entry as an available option
2. Assign the field to an asset volume
3. View available fields for an uploaded asset by double-clicking on the image preview (to load in a modal display)

### Expected result
Entry type will container a "+ Choose" button to select an entry.
![Screen Shot 2020-08-24 at 3 04 19 PM](https://user-images.githubusercontent.com/1728770/91101045-26579180-e61b-11ea-8c1e-680733ed0cd5.png)

### Actual result
Entry type is missing "+ Choose" button.
![Screen Shot 2020-08-24 at 3 02 01 PM](https://user-images.githubusercontent.com/1728770/91100939-ec868b00-e61a-11ea-89de-601c12ffec96.png)

## Details
Craft CMS v3.5.5
Typed LInk Field v1.0.23

**Comment by sebastian-lenz** [comment]
Huh, maybe the field is simply to small and the button gets cut off, maybe it is related to #119. Does the "Choose"-Button correctly show up in other locations within the control panel?

**Comment by TheFunkyMonk** [comment]
Yep, that was it. Also noticing this happens when using the new field layout editor with a Link field set to a shorter width, which will probably be a more common use case. Maybe possible to swap `.linkfield--elementRow` to `flex-flow: column;` in certain scenarios?

**Comment by sebastian-lenz** [comment]
Okay, I'll close this issue for now then. There is already a discussion about the display issues in small forms, please see https://github.com/sebastian-lenz/craft-linkfield/issues/64
