### ISSUE TITLE
Undefined index: entry on version restore

### ISSUE THREAD

**Issue by miro94** [sebastian-lenz/craft-linkfield#12]
If I select an older version of an entry:

![entry](https://user-images.githubusercontent.com/19932813/37031530-6f0f03b6-213f-11e8-84c6-d36a42f815f2.png)

The following error appears, related to the linkfield plugin

![screenshot at marz 06 13-06-26](https://user-images.githubusercontent.com/19932813/37031485-33c4e03c-213f-11e8-8260-67e8b21921d9.png)

PHP 7.2.3 / Craft 3.0.0-RC13 / Plugin Version 1.0.4

Let me know, If you need further informations.
Thanks!

**Comment by jamealg** [comment]
Same issue with PHP 7.0.15 / Craft Pro 3.0.0-RC10.1 / Plugin 1.0.3. Replacing the highlighted line with this appears to fix it:

`    return $linkTypes[$type]->getLinkValue($data['value']);`

**Comment by sebastian-lenz** [comment]
Thanks for reporting this!
