### ISSUE TITLE
Make v.2.0 compatible with `craftcms/gatsby-source-craftcms`

### ISSUE THREAD

**Issue by monachilada** [sebastian-lenz/craft-linkfield#125]
When using the new official [Gatsby Source plugin for Craft CMS](https://github.com/craftcms/gatsby-source-craftcms) from Pixel & Tonic, the type definitions for the `element` attribute returns unexpected or recursive definitions that result in massive and un-runnable introspection queries that fail, preventing the successful completion of the `sourceNodes` task in the plugin's `gatsby-node.js` file.

**Comment by monachilada** [comment]
Something about the definition of the `element` attribute [here](https://github.com/sebastian-lenz/craft-linkfield/blob/1feed925bfc6ab487edd6115975291a33db47dc4/src/models/LinkGqlType.php#L50) is resulting in the strange doubled or recursive results.

**Comment by sebastian-lenz** [comment]
Ho @monachilada, thank you for getting in touch. I've just checked the GraphQL type returned by this plugin and it seems to work like intended, you can fetch link and element data of link fields and for element links it returns a completely transparent reference to the element:

![graphql-test](https://user-images.githubusercontent.com/2273359/99881877-a8f0ec80-2c1c-11eb-8445-d48b3c3745f5.png)

The GraphQL API is a general purpose API built into Craft CMS and we cannot change / tailor the output of it for a single other project. So if there is an issue in another project, maybe you should open a bug report over there. If there is an issue in this plugins code I am happy to fix it or accept a pull request. However, you pull request just removed an attribute from the returned GraphQL type which does not seem like an adequate solution to me.

**Comment by monachilada** [comment]
Hey @sebastian-lenz Thanks for the response. I posted this when the Craft Gatsby plugin was still in active development. The plugin has come along since then so that custom fragments can be provided, effectively mitigating the issue I was describing here. So I think this can be closed. Thanks.
