### ISSUE TITLE
Making field required blocks saving as entry type

### ISSUE THREAD

**Issue by devotoare** [sebastian-lenz/craft-linkfield#126]
When creating a link field in a matrix and making it required, selecting an entry under entry type does not satisfy requirements for being filled out.

I tried with everything else except categories and it works fine (assets/sites specifically, since they are selected, both work).

Screenshot:
https://i.imgur.com/lLCJHdP.png

**Comment by sebastian-lenz** [comment]
Hey, @devotoare, thanks for reporting this. After looking into this I can confirm that there is a bug on required element link fields which have the element cache option enabled.

**Comment by sebastian-lenz** [comment]
Okay, I've patched this behavior, the link field will now be considered as valid if an element is selected.

The original code did not correctly take cached elements into consideration. Additionally, the validation required an element to actually return an url. This has also been changed, the field is now considered filled in as soon as an element is selected.
