### ISSUE TITLE
Add option for anchor tag

### ISSUE THREAD

**Issue by Envaya** [sebastian-lenz/craft-linkfield#127]
I want a link to be able to direct the user directly to a certain part of a page, like a specific FAQ question for example. To do that, I need to be able to add id anchors to my link.
Example:
www.mysite.com/faq#howtosignup

The field needs an option to either add an anchor or just a general custom input field one could use for purposes like this.

**Comment by sebastian-lenz** [comment]
Hi @Envaya, both is possible with a LinkField:

- For entry link types turn on the option "Allow users to enter custom queries that will be appended to the url". The user can enter queries and hashes in an additional input field next to the entry select field.

- For completely free and custom urls enable the custom link type.

![Bildschirmfoto 2020-10-09 um 18 30 49](https://user-images.githubusercontent.com/2273359/95608735-dc592c80-0a5d-11eb-9b2d-c0176d60db38.png)
