### ISSUE TITLE
Site link type doesn't work if base URL is an environment variable

### ISSUE THREAD

**Issue by ItagMichael** [sebastian-lenz/craft-linkfield#128]
Hi,

I have a site with the Base URL set to be an environment variable $DEFAULT_SITE_URL.

When using a link type of _Site_, and selecting this site, the link output is literally `<a href="$DEFAULT_SITE_URL">...</a>`. Am I just misunderstanding how this should work here?

Craft 3.4.30, craft-linkfield 1.0.23

**Comment by sebastian-lenz** [comment]
Hi @ItagMichael, thanks for reporting this. I've changed the site link type to correctly return site urls containing environment variables.

**Comment by NixonGit** [comment]
Could we get a new release with this fix?

**Comment by sebastian-lenz** [comment]
I'll release a new version as soon as I've checked upon the other issues.
