### ISSUE TITLE
Visually group fields together

### ISSUE THREAD

**Issue by timkelty** [sebastian-lenz/craft-linkfield#13]
I think it would help if you visually grouped all the fields…right now additional fields ("Custom link text", "Open link in new window") look like totally separate fields, when they should be grouped with the main link input.

![screen shot 2018-03-07 at 12 18 02 pm](https://user-images.githubusercontent.com/18329/37107237-d24100b6-2201-11e8-8da3-3899584b2690.png)

**Comment by sebastian-lenz** [comment]
I like the idea.

**Comment by sebastian-lenz** [comment]
Okay, next version will display a border if the link field has additional settings.
