### ISSUE TITLE
Change a linked disabled entry behaviour

### ISSUE THREAD

**Issue by TomDeSmet** [sebastian-lenz/craft-linkfield#131]
If a linked entry is disabled, the returned url is now the siteUrl. But it would be nicer if it would act as if the link field was empty.

**Comment by sebastian-lenz** [comment]
Hi @TomDeSmet, I just checked this behaviour and for me links that point to disabled elements do not return an url.

Could you share your Craft and plugin versions and some more details on your use case so I can reproduce the issue?

**Comment by sebastian-lenz** [comment]
I'll close this as I could not recreate the issue and now additional information has been given.
