### ISSUE TITLE
getLinkAttributes should return an object

### ISSUE THREAD

**Issue by timkelty** [sebastian-lenz/craft-linkfield#132]
Given Craft's `attr` function, filter, and `tag` tag, it would be nicer if `getLinkAttributes` returned an object instead, and leave the stringifying to those methods.

That would allow you do render links like so (and easily override attrs),

```
{{ tag('a', linkField.getLinkAttributes()) }}
```

**Comment by sebastian-lenz** [comment]
Hi @timkelty, [`getLinkAttributes`](https://github.com/sebastian-lenz/craft-linkfield/blob/master/src/models/Link.php#L236) is actually a thin wrapper that calls `Html::renderTagAttributes` under the hood. You can receive the raw attribute object using [`getRawLinkAttributes`](https://github.com/sebastian-lenz/craft-linkfield/blob/master/src/models/Link.php#L268). It has the same signature and behavior but returns an object.

**Comment by sebastian-lenz** [comment]
Both methods allow attributes to be overwritten by passing an object to the methods:

```
{{ tag('a', linkField.getRawLinkAttributes({
  target: '_blank'
})) }}
```

**Comment by sebastian-lenz** [comment]
And, just as a sidenote, the long method name `getLinkAttributes` was chosen cause the link class itself is a Yii model class which already declares a `getAttributes` method for retrieving the model data attributes.

...I think that's it ;)

**Comment by timkelty** [comment]
PERFECTO! thanks, @sebastian-lenz
