### ISSUE TITLE
Custom query not included with getUrl() or getLinkAttributes() methods

### ISSUE THREAD

**Issue by TheFunkyMonk** [sebastian-lenz/craft-linkfield#133]
# Description

Maybe I'm missing an option I need to enable, but getting a URL using either the `getUrl()` or `getLinkAttributes()` methods isn't containing custom queries if they're available.

# Behavior

Given a link field with an entry link to the homepage `https://www.test.com` and a custom query `anchor-link`:

### Expected Behavior

Template code:
```
<a href="{{ linkField.getUrl() }}">
```
Should output:
```
<a href="https://www.test.com#anchor-link">
```

### Actual Behavoir
Template code:
```
<a href="{{ linkField.getUrl() }}">
```
Outputs:
```
<a href="https://www.test.com">
```

# Additional Information

The custom query is available in the returned object, so in this situation, I can get manually include the query with something like:
```
<a href="{{ link.getUrl() ~ (link.customQuery ? '#' ~ link.customQuery) }}">
```
Though this gets pretty cumbersome when using something like `getLinkAttributes()` which automatically includes the href along with the other attributes. Am I just missing an option I need to pass these methods, or is this a bug?

Craft CMS: v3.5.18
Typed link field: v1.0.24

**Comment by sebastian-lenz** [comment]
Hi @TheFunkyMonk, the field "customQuery" expects the input to either start with `#` or `?`. As you are adding the hash manually here I guess your field only contains the hash value? Does it work as expected when you prefix the field value with `#`?

The field actually parses the value of the field customQuery using [parse_url](https://www.php.net/manual/de/function.parse-url.php) and merges the results, (at least [kind of](https://github.com/sebastian-lenz/craft-linkfield/blob/master/src/models/element/ElementLink.php#L113)). If the field does not contain something `parse_url` understand, nothing will happen.

**Comment by TheFunkyMonk** [comment]
Oh duh, that makes sense. And yes, totally works if I add the `#`. Thanks for clarifying!
