### ISSUE TITLE
Add a way to get link attributes as associative array

### ISSUE THREAD

**Issue by Mosnar** [sebastian-lenz/craft-linkfield#135]
With Craft 3.6, we've got a new Twig tag called `tag` that makes handling conditional container elements much easier. It'd be great if the plugin could easily output all of the html attributes we might need as an associative array to pass directly to this.

Perhaps this could be as simple as adding a boolean parameter to `getLinkAttributes()` to output as an array instead of a string.

For example...

Before:

```twig
{% if link.isEmpty() %}
<div id="image-popup">
{% else %}
<a {{link.getLinkAttributes()}} id="image-popup">
{% endif %}
<img src="image.jpg" />

{{ link.isEmpty() ? '</div>' : '</a>' }}
```

```twig
 {# Perhaps passing "true" to getLinkAttributes() could output as an array #}
{% set tagAttributes = link.isEmpty() ? {} : link.getLinkAttributes(null, true) %}
{% set tagType = link.isEmpty() ? 'div' : 'a' %}
{% tag tagType with tagAttributes|merge({id: 'image-popup'}) %}
    <img src="image.jpg" />
    <span>Here's an image that might be clickable!</span>
{% endtag %}
```

An added bonus is that this also helps abstract reusable components with Links. For example, we no longer have to individually pass all of the attributes or a Link model:

```twig
{% include 'card.twig' with {
    linkAttributes: item.linkField.getLinkAttributes(null, true),
    linkText: item.linkField.getText(),
    image: item.image.one()
} %}
```

This could also be very helpful to have in GraphQL for our headless folks.

**Comment by sebastian-lenz** [comment]
Hi @Mosnar! Actually [`getLinkAttributes`](https://github.com/sebastian-lenz/craft-linkfield/blob/4651157269ecae048e2d67107c0e74983ea9a02d/src/models/Link.php#L232) is a wrapper around the helper [`getRawLinkAttributes`](https://github.com/sebastian-lenz/craft-linkfield/blob/4651157269ecae048e2d67107c0e74983ea9a02d/src/models/Link.php#L268) which calls the same `Html` helper as the new twig tag function. So you can use `getRawLinkAttributes` to retrieve the attributes as an array that can be passed to the twig `attr` or `tag` functions.

**Comment by Mosnar** [comment]
Ahah, you're right! Thanks!
