### ISSUE TITLE
Get linktype from template?

### ISSUE THREAD

**Issue by alexr8** [sebastian-lenz/craft-linkfield#136]
Hi, great plugin - I was just wondering if its possible to get the link type from a template? I'd like to output different markup if the link type is mail / telephone / url etc. but couldn't see a way to check that in the available options?

**Comment by sebastian-lenz** [comment]
Hey @alexr8, you can get the link type using the attribute "type":
```
{% if myLink.type == 'url' %}
  ...
{% else %}
  ...
{% endif %}
```

**Comment by alexr8** [comment]
great, thanks @sebastian-lenz

**Comment by sebastian-lenz** [comment]
Okay, so if it works for you I'll close this issue for now. If you run into other issues please feel free to open an new one.
