### ISSUE TITLE
Remove icon is incorrectly positioned

### ISSUE THREAD

**Issue by darylknight** [sebastian-lenz/craft-linkfield#140]
Just noticed on a site running Craft 3.6.5.1 and Typed link field 1.0.24 that the 'remove' icon doesn't appear in the correct place when hovering over an entry.

Not hovering:

![image](https://user-images.githubusercontent.com/1250017/107638185-e68f6f80-6c77-11eb-8d2e-77c7371b019b.png)

Hovering:

![image](https://user-images.githubusercontent.com/1250017/107638207-ed1de700-6c77-11eb-9d43-69ab2a9694ee.png)

It looks like the close icon is appearing behind the green circle. Expected behaviour:

![image](https://user-images.githubusercontent.com/1250017/107638351-222a3980-6c78-11eb-93e9-15eecc5b32c2.png)

**Comment by sebastian-lenz** [comment]
Hm, I'll have to install some updates to take a look at this.

**Comment by Mosnar** [comment]
This may just be a Craft bug - https://github.com/craftcms/cms/issues/7549

**Comment by darylknight** [comment]
Yeah I think you're right. Link FIeld hasn't changed; think it's a Craft bug

**Comment by brandonkelly** [comment]
Craft 3.6.6 is out now with a fix for https://github.com/craftcms/cms/issues/7549.

**Comment by sebastian-lenz** [comment]
Great, thank you all for your time and great help!
