### ISSUE TITLE
Composer 2 psr-4 autoloading standard on sebastian-lenz/craft-utils

### ISSUE THREAD

**Issue by kylecotter** [sebastian-lenz/craft-linkfield#143]
Hi! Updated some composer packages and got a 

```
Class lenz\craft\utils\models\ModelArrayValidator does not comply with psr-4 autoloading standard.
```

message today with Composer 2. Seems to stem from the latest additions in the https://github.com/sebastian-lenz/craft-utils repo.

Thanks!

**Comment by sebastian-lenz** [comment]
Thanks for the heads up, I've fixed the namespace in the package `craft-utils`. Luckily that warning does not affect this plugin as the namespace is not used here.
