### ISSUE TITLE
Asset link type sources in project config don't match volume UIDs

### ISSUE THREAD

**Issue by sidm1983** [sebastian-lenz/craft-linkfield#144]
I have a Craft CMS site running in headless mode and I am using the Typed Link Field plugin (version 2.0.0-beta.12).

When I customise the asset link type in the link field to only allow picking of assets from certain asset sources, I get the following in my project config:
```
- asset
-
  __assoc__:
    -
      - enabled
      - true
    -
      - allowCustomQuery
      - false
    -
      - allowCrossSiteLink
      - false
    -
      - sources
      -
        - 'folder:ffb39844-f556-4c29-b4a8-7b181bf72ec1'
```
This looks fine on the surface, however, I have now realised that the UID being referenced by `folder:ffb39844-f556-4c29-b4a8-7b181bf72ec1` does not match the UID of the volume I have selected. It seems to be using a different UID and not the UID or handle of the selected volume from the YAML in the `volumes` project config folder. In other words, the UID being referenced here cannot be found anywhere else in any of the project config YAML files. The YAML filename of the asset volume referenced above is actually `documents--75d8bc6f-c819-4a59-b465-84f8496d9f39.yaml`, so I am expecting the above reference to be `folder:75d8bc6f-c819-4a59-b465-84f8496d9f39` instead of what it is above.

As a result of this, every time I do a clean install of Craft CMS (e.g. when a new developer joins the team or freshly setting up a different environment like QA, UAT or PROD), that database doesn't end up having this UID and so none of my previously selected asset sources get preselected after a fresh Craft CMS install. The UID used above seems to be a dynamic UID that changes every time Craft is freshly installed.

In contrast, the "Entry" link type correctly uses the UID of the section it is referencing as seen in the filename of the section's project config YAML. For example, my entry source for the same link field above is `section:47f8d07e-c48a-4ec2-8420-36ea82eb50ba` and the YAML filename of this section is `article--47f8d07e-c48a-4ec2-8420-36ea82eb50ba.yaml` which match up correctly.

Please fix this issue as this is causing all my environments to not have the asset sources preselected because they don't have the same UID being referenced by the asset sources in the project config for the asset link type.

Also, just in case it matters, my asset volumes are all remote volumes that store the underlying files in Azure Blob Storage using the Azure Blob Remote Volume plugin in the plugin store (https://plugins.craftcms.com/azure-blob-remote-volume).

Any thoughts or help in fixing this soon would be greatly appreciated.

Thank you 🙏🏽 

Craft CMS version: 3.6.4.1
Type Linked Field version: 2.0.0-beta.12
Azure Blob Remote Volume version: 1.1.1
PHP version: 7.3
Database driver & version: PGSQL 11

**Comment by sidm1983** [comment]
Hi @sebastian-lenz, just checking to see if you have any thoughts about this issue. Please let me know when you get a chance. Thank you. 🙏🏽

**Comment by sebastian-lenz** [comment]
Hey @sidm1983, no need to put pressure on me. This plugin is free and open source and if you need a change quickly you are free to fork and adjust the code to your liking.

As your snippet from the project configuration shows, we currently store the folder identifier (`folder:ffb39...`) when selecting particular assets sources. We do this for quite a long time as that format is expected by the ui element for selecting elements exposed by the CMS.

Unfortunately the folder ids change between different Craft instances as they are not part of the project configuration. There is a volume identifier though that stays the same. So it would make sense we switch the source storage on our side from the folder to the volume ids.

**Comment by sidm1983** [comment]
@sebastian-lenz, I was definitely not trying to put pressure on you. Sorry if it came across that way and made you feel pressured. 🙏🏽

I am definitely super appreciative for the plugin as it helps simplify content entry for links in my entry types. Thanks for creating this plugin. 🙌🏽

I do normally help out and contribute where I can, however, I am very new to Craft CMS & PHP in general, so I didn't want to make a mess of things.

Thank you for doing the switch to volume IDs so quickly. It is definitely appreciated.

Do you mind guiding me on how to get this new update so I can help with testing it? Should I wait for a new beta 13 version to be released or is there a way to pull this commit directly using composer? Again, no pressure. I am just trying to learn more about Craft/PHP in general so I can contribute in the future. Please let me know when you get a chance.

Thank you. 🙏🏽

**Comment by sidm1983** [comment]
@sebastian-lenz, just reporting back. I tried to install v2.0.0-beta.13, however, composer couldn't find the beta 13 version. I got the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires sebastianlenz/linkfield ^2.0.0-beta.13, found sebastianlenz/linkfield[dev-master, 1.0.1, ..., v1.0.x-dev, 2.0.0-beta.1, ..., 2.0.0-beta.12] but it does not match the constraint.
```

Please let me know when beta 13 is available or if there is another way for me to get your updates.

Thank you.

**Comment by sebastian-lenz** [comment]
Hi @sidm1983, i did not tag a version beta.13 yet so it is not available. If you want to access the changes early, you can upgrade to `dev-master` which will install the latest available version:

```json
"require": {
  "sebastianlenz/linkfield": "dev-master",
}
```

You can also directly point to the commit that contains the new feature, which ensures you won't update to other upcoming pre-release versions: 

```json
"require": {
  "sebastianlenz/linkfield": "dev-master#ced723f",
}
```

If you do so, you should remember to remove that line and return to the version `2` tag once version 13 is out so you get updates after that.

**Comment by sidm1983** [comment]
@sebastian-lenz thank you. I will try it today and let you know how I go. 🙌🏽👍🏽

**Comment by sidm1983** [comment]
@sebastian-lenz, I have been testing your recent updates and I have found an issue.

When I explicitly select one or more asset sources while configuring the link field, the asset picker on the asset link field type doesn't show any assets. The asset picker modal loads when I click the "+ Choose" button, but then none of the assets in the allowed volumes show up. Please see the following screenshots.

Here is a screenshot of my "Asset" type configuration in the link field:
![image](https://user-images.githubusercontent.com/45752844/109930398-b9d0f400-7d1b-11eb-9570-6c26ec2b465e.png)
As you can see, I have selected "Documents" as the only allowed asset source for the asset link type.

Here you can see that I actually have a document in my "Documents" volume:
![image](https://user-images.githubusercontent.com/45752844/109930642-fac90880-7d1b-11eb-9c80-ff4e23bdc7b7.png)

And lastly, here is the asset picker modal that comes up when I click the "+ Choose" button for an asset link type:
![image](https://user-images.githubusercontent.com/45752844/109930865-3bc11d00-7d1c-11eb-8d94-d1aebbf5d5f1.png)

I believe this used to work before when it was still using folder UIDs, but has stopped working since the switch to volume UIDs.

If I select "All" as the allowed asset sources for the asset link type, then the asset picker modal works and displays all volumes/assets.

Could you please test on your end and see if you are able to replicate this issue as well?
Please let me know when you get a chance.

Thank you! 🙏🏽

**Comment by sebastian-lenz** [comment]
Ah, I'm sorry, I missed something while cleaning up my code mess. We must transform the volume ids before sending them to element select, I've added that part back to the plugin. The volumes now correctly show up for me.

**Comment by sidm1983** [comment]
No worries at all @sebastian-lenz. I will pull your latest updates and test them soon. Will let you know how I go. Thank you.

**Comment by sidm1983** [comment]
@sebastian-lenz I just tested this and it is working again now. Asset modal now shows the correct volume and assets and also the volume UID switch is working and pre-selecting the correct volumes on my QA environment. Closing this issue now. Thank you. 🙏🏽

**Comment by sebastian-lenz** [comment]
That's great to here. Thank you for your feedback.
