### ISSUE TITLE
Fallback to Craft Url

### ISSUE THREAD

**Issue by hugo-costa** [sebastian-lenz/craft-linkfield#149]
Hi,

I would like to know if its somehow possible if an entry has the Linkfield field but the field has not be set a value, if the url can fall back to the default Craft url? (`entry.url`)?

I tried several `if` conditions and could not get this to work?

**Comment by sebastian-lenz** [comment]
Hi @hugo-costa, most model methods won't return anything if the field is empty and does not contain an url, so depending on what you want to do you might use the twig `default` filter:

```twig
<a href="{{ entry.myLinkField.url|default(entry.url) }}">Read more...</a>
```

You can also check whether the link has an url using the `isEmpty` helper. This might be especially helpful if you want to use the `linkAttributes` helper as it will only return attributes if the link is set.

```twig
{% if entry.myLinkField.isEmpty %}
  <a href="{{ entry.url }}">Read more...</a>
{% else %}
  <a{{ entry.myLinkField.linkAttributes }}>Read more...</a>
{% endif %}
```
