### ISSUE TITLE
Add formie as a link option - enhancement

### ISSUE THREAD

**Issue by anchovy** [sebastian-lenz/craft-linkfield#150]
If we could get forms from [formie](https://github.com/verbb/formie) added as an option that would be amazing.

### Use case.
We use the link field to set the element for buttons. If a formie form is selected, we'll open this in a modal. We've got clumsy workaround at the moment (new entry type of form, which has a formie form selected), but this causes duplication.

Thanks in advance.

**Comment by sebastian-lenz** [comment]
Hi @anchovy, as far as I can tell from skimming through the docs, Formie does not expose forms to public urls. Instead the forms must be placed within a template or can be placed using the integrated form select field. Therefore it does not make sense to offer Formie as a default option within the link field.

If it makes sense for your project you can easily add the form elements exposed by Formie to the link field, we have a simple example in the [readme](https://github.com/sebastian-lenz/craft-linkfield#api). Somewhere within the bootstrap code of your site you have to do something like this:

```php
Event::on(
  lenz\linkfield\Plugin::class,
  lenz\linkfield\Plugin::EVENT_REGISTER_LINK_TYPES,
  function(lenz\linkfield\events\LinkTypeEvent $event) {
    $event->linkTypes['verbbFormie'] = new lenz\linkfield\models\element\ElementLinkType([
      'displayGroup' => 'Verbb Formie',
      'elementType'  => 'verbb\formie\elements\Form',
    ]);
  }
);
```
