### ISSUE TITLE
Using getLink() causes emails to have // after mailto:

### ISSUE THREAD

**Issue by zizther** [sebastian-lenz/craft-linkfield#151]
I am using craft-linkfield version 2.0.0-rc.1, I am outputting an email link using `.getLink()` this is causing the email string in the href to output as `mailto://`

**Comment by sebastian-lenz** [comment]
Hi @zizther, thanks for reporting this. There indeed seems to be a bug that assembles mailto links incorrectly when trying to modify them. I've adjusted the way mailto links are assembled.

**Comment by zizther** [comment]
@sebastian-lenz Is it possible to use 2.0.0-rc.2 with this fix yet?

**Comment by sebastian-lenz** [comment]
Yeah, the change did not affect this plugin directly, but instead one of the dependencies. I've updated the dependency "sebastian-lenz/craft-utils" to version "2.3.1" which contains the fix:
https://github.com/sebastian-lenz/craft-utils/blob/master/src/models/Url.php

You should receive the fix by running `composer update`.
