### ISSUE TITLE
GraphQL: Expose all link field data 

### ISSUE THREAD

**Issue by wrux** [sebastian-lenz/craft-linkfield#158]
### Problem

I am querying my data in and the typed link field only returns a string. 

In Craft you can specify the link text, if it should open in a new tab, aria label and various other things, however these are not exposed to the GraphQL API. 

Does this need to be configured on my end or is the feature planned for a future release?

### System info

- PHP version: 7.4.14
- Typed link field: 1.0.25

**Comment by mildlygeeky** [comment]
So this has been present on the `master` branch here on GitHub for a while, but you can only get it by setting your constraint to `dev-master` in composer.json.

@sebastian-lenz - any reason this has not yet been put into a finished release? I don't love being on non-production releases, but this GQL support has been both necessary and rock-solid for us for months.

**Comment by sebastian-lenz** [comment]
Hi @wrux, v1 of the plugin supports the legacy GraphQL plugin, if you want to use the native GraphQL support of Craft you have to switch to version 2.

@mildlygeeky You should not have to set your dependency to `dev-master`, this is indeed dangerous as you'll receive all commits that are pushed to this repository. I release new versions of v2 to packagist that are intended to be used, see https://packagist.org/packages/sebastianlenz/linkfield. You should be able to require v2 by specifying a [stability flag](https://getcomposer.org/doc/04-schema.md#package-links):
```
{
    "require": {
        "sebastianlenz/linkfield": "2.*@rc"
    }
}
```

As a lot of Craft sites use this plugin, I am extra cautious before finally releasing this update, sorry about that.

**Comment by teamteak** [comment]
Hey - any plans on releasing 2.x soon? We love your plugin, but it's limiting in our Headless CMS site....and it's been 6 months. 

Do you need help testing?
