### ISSUE TITLE
getType() does not seem to exist

### ISSUE THREAD

**Issue by scandella** [sebastian-lenz/craft-linkfield#159]
Using `{{ entry.myLinkField.getType() }}` I've got an error: `Calling unknown method`.
I have to use `entry.myLinkField.getLinkType.elementType }}` to make it work.

Is this the way it should behave?

Thanks for your help.

**Comment by thijskaspers** [comment]
Noticed this too, but `.type` seems to work? `{{ entry.linkfield.type }}`

**Comment by sebastian-lenz** [comment]
Hi @scandella, `type` is actually an attribute (not a method) on the link model, you can access it like @thijskaspers explained it using `{{ entry.myLinkField.type }}`. You can access the linked element type like you've shown in your example too, but you should make sure that the link actually points to an element or you'll raise an error.

**Comment by sebastian-lenz** [comment]
BTW, the method `getType()` was introduced in version 2 of the plugin. I guess you are still using version 1.

**Comment by scandella** [comment]
> BTW, the method getType() was introduced in version 2 of the plugin. I guess you are still using version 1. 

OK!  Because the `getType()` method is already in the current documentation, I thought it was available in the production version 1.025 that I'm using. Sorry…  
`{{ entry.myLinkField.type }}` works fine.

Thanks for your help.
