### ISSUE TITLE
Create a custom link type that has a default 'id' set

### ISSUE THREAD

**Issue by thijskaspers** [sebastian-lenz/craft-linkfield#160]
Hey there,

I'm trying to create a custom link type that will automatically have an `id=""` set to a certain ID. The link doesn't need a href or any other options, just an id.

Our client is using chat software, and wants to be able to trigger a chat via buttons that they add on the website. Sometimes they link to an entry, sometimes they create a link to an external URL, but they also need the option for a "Chat trigger" button too. The chat software is installed through the Google Tagmanager and listens to an onclick on buttons with a certain 'id', after which it will pop up.

I've already created a custom linktype, but am stuck on how to give this button an 'id' when it renders through the getLink() method. I could ofcourse check the linktype in Twig and add a fixed 'id' there, but that is not ideal to do for every button on the website.

Any method I can use that hooks into the rendering of the button (`getLink()`) and can add an 'id' to it when it's my custom linktype? Any help to point me in the right direction is highly appreciated :) thanks!

**Comment by sebastian-lenz** [comment]
Hi @thijskaspers, link types cannot control the way links a rendered, this case has not been encountered this far. The composition of the link attributes happens within our common [link model](https://github.com/sebastian-lenz/craft-linkfield/blob/master/src/models/Link.php#L270) while the link type itself only contributes the url.

I would suggest to either build a common template helper or to attach a custom behavior to the link model to customize the link rendering.
