### ISSUE TITLE
Craft is having trouble merging in changes to drafts with link fields

### ISSUE THREAD

**Issue by Mosnar** [sebastian-lenz/craft-linkfield#161]
I'm not exactly sure what's going on here, but it seems like Craft is having trouble merging in changes from drafts with Link Fields. Oddly enough, the live preview works, but the "Save" action does not. If I duplicate the exact entry and resave the copy, it works. I imagine this is because the changes on the canonical element are no longer present on the duplicate.

I was able to reproduce the issue like so:
1. Create an entry type with a link field
2. Create an entry with that type and fill in the link filed, publish it
3. Create a new draft and change some field value
4. Go back to the live entry and make a change to the title attribute, publish the change
5. Go back to your draft and click "Apply Draft"
6. See error

Here's the stack trace associated:
```
TypeError: lenz\linkfield\fields\LinkField::toRecordAttributes(): Argument #2 ($element) must be of type craft\base\ElementInterface, null given, called in /var/www/project/cms/vendor/sebastianlenz/craft-utils/src/foreignField/ForeignField.php on line 172 and defined in /var/www/project/cms/vendor/sebastianlenz/linkfield/src/fields/LinkField.php:299
Stack trace:
#0 /var/www/project/cms/vendor/sebastianlenz/craft-utils/src/foreignField/ForeignField.php(172): lenz\linkfield\fields\LinkField->toRecordAttributes(Object(lenz\linkfield\models\element\ElementLink), NULL)
#1 /var/www/project/cms/vendor/craftcms/cms/src/base/Field.php(560): lenz\craft\utils\foreignField\ForeignField->serializeValue(Object(lenz\linkfield\models\element\ElementLink))
#2 /var/www/project/cms/vendor/craftcms/cms/src/base/Element.php(2260): craft\base\Field->copyValue(Object(craft\elements\Entry), Object(craft\elements\Entry))
#3 /var/www/project/cms/vendor/craftcms/cms/src/services/Elements.php(811): craft\base\Element->mergeCanonicalChanges()
#4 [internal function]: craft\services\Elements->craft\services\{closure}(Object(craft\db\Connection))
#5 /var/www/project/cms/vendor/yiisoft/yii2/db/Connection.php(810): call_user_func(Object(Closure), Object(craft\db\Connection))
#6 /var/www/project/cms/vendor/craftcms/cms/src/services/Elements.php(834): yii\db\Connection->transaction(Object(Closure))
#7 /var/www/project/cms/vendor/craftcms/cms/src/controllers/EntriesController.php(737): craft\services\Elements->mergeCanonicalChanges(Object(craft\elements\Entry))
#8 /var/www/project/cms/vendor/craftcms/cms/src/controllers/EntriesController.php(628): craft\controllers\EntriesController->_loadEntry(Object(craft\models\Site), Object(craft\models\Section), 6073, NULL, NULL)
#9 /var/www/project/cms/vendor/craftcms/cms/src/controllers/EntriesController.php(80): craft\controllers\EntriesController->_prepEditEntryVariables(Array)
#10 [internal function]: craft\controllers\EntriesController->actionEditEntry('pages', 6073, NULL, NULL, 'redacted', NULL)
#11 /var/www/project/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/project/cms/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/project/cms/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-entry', Array)
#14 /var/www/project/cms/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-entry', Array)
#15 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(271): yii\base\Module->runAction('entries/edit-en...', Array)
#16 /var/www/project/cms/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('entries/edit-en...', Array)
#17 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(256): yii\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/www/project/cms/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /var/www/project/cms/web/index.php(22): yii\base\Application->run()
#20 {main}
```

Versions:
Typed link field: 2.0.0-rc.1
Craft: 3.7.0
PHP: 8.x

**Comment by Mosnar** [comment]
@sebastian-lenz Seems like this may actually be a simple PHP 8 compatibility issue rather than a 3.7 issue. 

https://github.com/sebastian-lenz/craft-utils/blob/0df1aec3891252c59af752d6c34f7fa46917f658/src/foreignField/ForeignField.php#L171-L173

This method signature should be:
`public function serializeValue($value, ?ElementInterface $element) {`

**Comment by Mosnar** [comment]
I looked into this a bit more and it seems the issue stems from the new `copyValue(ElementInterface $from, ElementInterface $to): void` method not providing the element to the serializeValue method. It's not technically required, so maybe it just needs to be tweaked. I wonder if there's a good reason for this or if it was just an oversight.

https://github.com/craftcms/cms/blob/cd1783b71b2cd6dd2fe839c628012147b081ba4c/src/base/Field.php#L558-L562

Perhaps @brandonkelly could weigh in?

Otherwise, the fix may be to just adjust the `toRecordAttributes` method to accept a null $element.
https://github.com/sebastian-lenz/craft-linkfield/blob/ef27aeb024b8747eb778b4276793d34b49c14921/src/fields/LinkField.php#L306-L314

**Comment by brandonkelly** [comment]
@Mosnar Yeah that’s an oversight. Just fixed that for the next release.

**Comment by brandonkelly** [comment]
Just released 3.7.4 with that fix. Thanks again!

**Comment by sebastian-lenz** [comment]
Thanks to both of you for having a look!

@Mosnar I'll leave it to you whether this ticket should be closed or not.

**Comment by Mosnar** [comment]
Looks like everything is working now as far as I can tell. Thanks guys!
