### ISSUE TITLE
Links to entries always point to default site

### ISSUE THREAD

**Issue by martinhellwagner** [sebastian-lenz/craft-linkfield#17]
We're currently developing a multi-site in Craft, and we're using this plugin to give the user the opportunity to link to URLs as well as entries. However, we seem to be running into two problems:

- When adding a disabled entry as a link, it is gone upon saving (is that intentional or not?)
- When adding an entry as a link in a site that is not the default one (e.g. "A"), the entry of the default site (e.g. Entry of "A") is taken instead of the entry of the non-default site (e.g. Entry of "B") that we are editing

When adding an entry that exists in both sites to a non-default site ("B") and the entry is disabled in the default site ("A") but enabled in the non-default site ("B"), it is gone because of the first and second bullet point playing together. However, it only seems to be gone in the backend, but not in the frontend (you can see it on the website).

Maybe you can help us out with this bug? That'd be much appreciated!

**Comment by sebastian-lenz** [comment]
Hey, indeed, did test with a multisite and the field shows and returns not the intended values. I've published an update.
