### ISSUE TITLE
Allow global link source

### ISSUE THREAD

**Issue by timkelty** [sebastian-lenz/craft-linkfield#18]
It would be great if there were a way to link to a global somehow.

For example, I have a site that references an external url several times, which I have in a global "URL" field.

I want to use Link Field, and be able to select that global as the link URL.

**Comment by sebastian-lenz** [comment]
You can do this by adding an additional link type via the plugin API, would be something like this:

```
$plugin = \typedlinkfield\Plugin::getInstance();
$linkType = new \typedlinkfield\models\ElementLinkType('globalSet');
$plugin->addLinkType('globalSet', $linkType);
```

I'm not sure whether it is a common scenario for other users and whether it should be included in the plugin.

**Comment by timkelty** [comment]
Oh nice! What's the right place to hook into this, after `\typedlinkfield\Plugin::init`, or should the plugin implement some sort of `EVENT_REGISTER_LINK_TYPES` event?

**Comment by sebastian-lenz** [comment]
Okay, I've added the `GlobalSet` element as a default link type. I've also added an event that can be used to register custom link types and adjusted the `README.MD` example accordingly.

**Comment by timkelty** [comment]
Woohoo, thanks!

**Comment by timkelty** [comment]
@sebastian-lenz Hmmmm the added GlobalSet type does not work for me. When I change a field to use it, the element index selector is always blank, yet I do have globalsets and globals…
![screen shot 2018-05-04 at 1 41 12 pm](https://user-images.githubusercontent.com/18329/39642806-d522fd12-4fa0-11e8-81fa-2691c878ea5a.png)

**Comment by sebastian-lenz** [comment]
I've just reviewed the global set element type of craft (didn't do anything with it previously). Actually I got confused between "Singles" and "Globals". When this issue arrised I was thinking of singles which are element types which always have only one instance. The globals mentioned in this issue are actually more like a way for developers to store configuration settings.

As globals don't have urls, it actually makes no sense in offering them as a target in a plugin that is designed to let users select links. I'll remove the global set from the list of available options.

**Comment by timkelty** [comment]
@sebastian-lenz that's a fair point, my use-case was pretty narrow.

In my case I had a global set with a URL field in it, and wanted to use that from Link Field.

**Comment by sebastian-lenz** [comment]
I was thinking about your issue yesterday. In an abstracted way, I think your problem could be solved by giving authors the possibility to select something like a "static" link. Like, a configurable dropdown with entries defined by the site like "Imprint" or "Contact", etc. 

If we add a clear API for programmers to consume those links elsewhere (allow them to be placed in a template, e.g. the footer) and a UI they can be managed with we have something like cool feature.
