### ISSUE TITLE
Ability to add additional data attributes

### ISSUE THREAD

**Issue by laurabennett** [sebastian-lenz/craft-linkfield#185]
Is there a way create a link like the following with your plugin? I would like to be able to set attribute name "data-accesso-keyword" in the field admin and then set the value in the entry.

<a class="btn-cta" href="#" data-accesso-keyword="Lift Tickets">GET TICKETS</a>

Thanks!!

**Comment by laurabennett** [comment]
I did set getLinkAttributes but not sure how to use it. What is it going to return that would make it helpful? How do I set the attributes?

**Comment by sebastian-lenz** [comment]
I've linked the example, something like this:

```
<a{{ entry.myLinkField.getLinkAttributes({
  'class': 'btn-cta',
  'data-accesso-keyword': 'Lift Tickets',
}) }}>
  GET TICKETS
</a>
```

**Comment by laurabennett** [comment]
Oh, so this is just setting attributes from the template? I was looking for a way to set the value "Lift Tickets" within the Link fields so that it would be dynamically set by the CMS. There are multiple options, I don't want it to be "Lift Tickets" in every instance.

**Comment by sebastian-lenz** [comment]
Sure, just create a separate text or select field next to the link field and use that value in the template.
