### ISSUE TITLE
Graph QL Support

### ISSUE THREAD

**Issue by davidhellmann** [sebastian-lenz/craft-linkfield#20]
Hey, do you plan GraphQL support?

**Comment by sebastian-lenz** [comment]
Hm, is that a thing right now? Facebook strikes again...

It's not planned, but the project is free and open source, so if someone wants to add support I would be happy to accept pull requests.

**Comment by timkelty** [comment]
@sebastian-lenz I'm using it with GraphQL and should be able to help!

It works pretty well as is, we'll just want to implement some of the getter methods as props (getText, etc)

**Comment by sebastian-lenz** [comment]
Sure, just create a pull request!

**Comment by sebastian-lenz** [comment]
Okay, thank you! You've removed two fields that are not interesting to GraphQL users, this looks like a breaking change too me. Can we leave them in there and mark them deprecated with GraphQL? So we could delay the final removal till version 2.0.

**Comment by timkelty** [comment]
@sebastian-lenz ah good call.

I updated the PR and put them back in.

**Comment by timkelty** [comment]
@sebastian-lenz I commented on #31 – not quite sure yet how to pull that off.

These changes should be non-breaking though, so maybe you can push a 1.x release first? 😇

**Comment by sebastian-lenz** [comment]
Okay, release is out
