### ISSUE TITLE
Get the ASSET type

### ISSUE THREAD

**Issue by wallythewebdev** [sebastian-lenz/craft-linkfield#202]
HI there - love the plugin - 

was wondering if you can get the ASSET file type? 

So once you have set a ASSET as the link type you can call the native craft .extension of that link? 

```
    {% set resourceLink = block.resourceLink %}
    {% if not resourceLink.isEmpty() %}
    {# Type - Download / URL #}
      <a class="btn" href="{{ resourceLink }}">
      {% if resourceLink.type == 'asset' %}
        Download {{ resourceLink.extension }} <<< this is not working but what I am trying to do is get the ASSETS file type extension 
      {% else %}
        Open site
      {% endif %}
      </a>
    {% else %}
      {# Type - link to entry #}
      <a class="btn" href="{{ block.url }}">Read more</a>
    {% endif %}
```

Any ideas or if this is possible would be great. 
(would just be cool to have a download svg or download PDF button)

Thanks

**Comment by sebastian-lenz** [comment]
Hi @wallythewebdev, you can check the type using the attribute `linkType`:

```
{% if resourceLink.linkType == 'asset' %}
  ...
{% else %}
  ...
{% endif %}
```

**Comment by wallythewebdev** [comment]
@sebastian-lenz amazing!!! 
thanks for the quick reply 👊👊👊👊

**Comment by sebastian-lenz** [comment]
Huh, I'm sorry, `linkType` return the internal class that manages that link, you should look at `type` for the string value, my fault:

```
{% if resourceLink.type == 'asset' %}
  {{ resourceLink.element.extension }}
{% else %}
  ...
{% endif %}
```

Once you are sure that the link points to an asset, you can access the linked element using the attribute `element`. It contains the complete element that has been linked to, you can access all fields and properties (like `extension`).
