### ISSUE TITLE
Issue when get up elements data.

### ISSUE THREAD

**Issue by aodihis** [sebastian-lenz/craft-linkfield#203]
Step to reproduce:
1. Create section with  a type link field with entry / category / another elements enabled.
2. Inside the entry details page, go to link field then choose either entry, category or any element type.
3. The modal is pop up but returning server error and no elements showing.

This probably caused when getting the elements indexes on `element-indexes/get-elements ` passing the `enabledForSite` criteria, that deprecated on since craft 3.5 and probably remove in craft 4. Instead using `enabledForSite` should be used `status` as criteria instead.
Thank you.

Craft version : 4.0.0-beta3
Plugin version: [1.1.0]

**Comment by sebastian-lenz** [comment]
See #204
