### ISSUE TITLE
Craft 4 - Fatal error

### ISSUE THREAD

**Issue by Toni-hr98** [sebastian-lenz/craft-linkfield#206]
Getting this error after opening a section with the linkfield attached to it.

Fatal error: Declaration of lenz\linkfield\models\Link::isEmpty() must be compatible with lenz\craft\utils\foreignField\ForeignFieldModel::isEmpty(): bool in /home/vagrant/Sites/sitename/backend/vendor/sebastianlenz/linkfield/src/models/Link.php on line 372

**Comment by Toni-hr98** [comment]
<img width="171" alt="Schermafbeelding 2022-04-03 om 20 06 26" src="https://user-images.githubusercontent.com/56109782/161442337-304fbd53-5fd6-497f-8d90-320c704ba7bf.png">

**Comment by Toni-hr98** [comment]
<img width="1169" alt="Schermafbeelding 2022-04-03 om 20 20 36" src="https://user-images.githubusercontent.com/56109782/161442352-99f8c022-c378-4e70-8b6d-29d95975fed9.png">

**Comment by kylecotter** [comment]
Can also replicate the same error on version [2.1.0-rc](https://github.com/sebastian-lenz/craft-linkfield/releases/tag/2.1.0-rc) running on Craft CMS 4.0.0-beta.4.

**Comment by mark-reactor15** [comment]
Just came across the same problem, looks like it's fixed in this commit but not pushed to a new version yet:
https://github.com/sebastian-lenz/craft-linkfield/commit/a8e134a4124946f9b7091ace00399279a9407b4d

**Comment by tremby** [comment]
I had a similar error when trying to create a new field, but it looks like it's fixed in a recent commit.

**Comment by davidhellmann** [comment]
@sebastian-lenz can u push a new version 🤔

**Comment by sebastian-lenz** [comment]
@davidhellmann Okay, I've released a new version.
