### ISSUE TITLE
Discontinued support for Craft 3

### ISSUE THREAD

**Issue by markmiddleton** [sebastian-lenz/craft-linkfield#207]
The recent update this plugin only supports the beta version of Craft 4.  

Has this plugin been discontinued for support on the current public production release version of Craft? (currently v3.7.38)

**Comment by sebastian-lenz** [comment]
It is not possible to release a single version that both supports Craft 3 and 4 due to the changed PHP language levels and APIs. Craft 3 will be supported on the version 1.0.x while Craft 4 will be supported on version 1.1.x.
