### ISSUE TITLE
1.1.0 update that does not support Craft 3 still shows up as an update in a Craft 3 install

### ISSUE THREAD

**Issue by japo32** [sebastian-lenz/craft-linkfield#208]
![Screen Shot 2022-04-07 at 2 38 57 PM](https://user-images.githubusercontent.com/676680/162109510-cdfd1a5f-bd7b-4087-b490-e9ae828fe6b6.png)

**Comment by sebastian-lenz** [comment]
Does it actually install the new version when you click "Update"?

**Comment by Antimated** [comment]
I'm not able to test right now :/ My project is still running php 7.4 so maybe @japo32 could answer your question.

**Comment by eheiser** [comment]
Why remove support for Craft3? A lot of us will be running v3 installs for quite some time yet...

**Comment by sebastian-lenz** [comment]
Yeah, sorry for the confusion, if you are using Craft 3 you should stick to version 1.0.x, if you are upgrading to Craft 4 you should switch to version 1.1x. The composer definitions of the versions correctly declare the dependencies, it seems like either composer does not behave like I thought it would or that the updater in the control panel does not check the requirements. I'll have to investigate this.

For the time being you can get rid of the error by explicitly setting the version to `1.0.*` in your `composer.json` file. Remember to remove the lock once you upgrade to Craft 4.

@eheiser It is not possible to release a single version that both supports Craft 3 and 4 due to the changed PHP language levels and APIs. Craft 3 will be supported with version 1.0.x while Craft 4 will be supported with version 1.1.x/2.1.x of this plugin.

**Comment by joshwalsh** [comment]
Also having this error where this 3.1 version of the plugin is showing up as an update in Craft 3.x and then cannot be installed.

As indicated, setting the composer.json value as follows allows composer to update, but still shows as an uninstalled update in the craft control panel.

```
"sebastianlenz/linkfield": "1.0.*"
```

**Comment by pixleight** [comment]
Might I suggest following semantic versioning? With a breaking change like requiring Craft 4.x, it should probably be bumped to `2.x.x` rather than `1.1.0`.

**Comment by sebastian-lenz** [comment]
@pixleight As we have a release candidate for version 2 already, I cannot tag the updated version of 1.0.* for Craft 4 like that. Also, the new version does not change the public API and therefore must not be tagged as a new major version I guess. Actually raising the minor version is mentioned as the default way of handling this, if I understand the docs correctly:
https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

**Comment by pixleight** [comment]
@sebastian-lenz interesting, apparently I had a misunderstanding of semver. I would have thought a breaking dependency change would be considered a major version increase.

**Comment by sebastian-lenz** [comment]
I'm unsure. I am aware of semantic versioning and try to raise the version number according to it. Again, I'm sorry for the confusion this is causing.

**Comment by joshwalsh** [comment]
No problem from my perspective.  We appreciate the plugin and your responsiveness.

**Comment by japo32** [comment]
Thanks for the responsiveness @sebastian-lenz.

**Comment by brandonkelly** [comment]
Hm, this shouldn’t be happening. I see your `craftcms/cms` constraint was set to `^4.0.0-beta` on the `1.1.0` commit (4a609e3ca991079b5ffd935d48f89ed3741debd4):

https://github.com/sebastian-lenz/craft-linkfield/blame/4a609e3ca991079b5ffd935d48f89ed3741debd4/composer.json#L8

Which should prevent the update from showing up for any Craft versions that don’t match that constraint (namely Craft 3.x).

Is there any chance that `1.1.0` was originally tagged for a different commit where `craftcms/cms` was set to `^3.x.x` instead?

**Comment by RyanRoberts** [comment]
Is there anything we can do in the meantime? I couldn't figure out how to explicitly set the version to avoid an update prompt.

**Comment by turnstylerj** [comment]
I'm also having this issue, which is breaking the Craft CLI command `php craft update all` on my Craft 3 site. Haven't touched anything related to Craft 4 yet. I feel like something was tagged incorrectly with this plugin update.

**Comment by estebancastro** [comment]
@turnstylerj for now I'm skipping this update checking first for the latest plugins updates with `php craft update` to later choose only the plugin that I want update, by example `php craft update retour`.

**Comment by turnstylerj** [comment]
Thanks @estebancastro yep, that's what I had to do as well. Definitely seems like this plugin needs an update according to @brandonkelly's [explanation above](https://github.com/sebastian-lenz/craft-linkfield/issues/208#issuecomment-1092305083) so the CLI works correctly again.

**Comment by sebastian-lenz** [comment]
Okay, for the time being I've revoked version `1.1.0`. If someone wishes to use Craft 4, please switch to version `1.1.0-beta`.

@brandonkelly No, there never was version 1.1 tagged for Craft 3. I currently have no idea why the version shows up in the update list.
