### ISSUE TITLE
Custom link text "Button cannot contain emojis."

### ISSUE THREAD

**Issue by jomotion11** [sebastian-lenz/craft-linkfield#211]
I tried adding an emoji in the custom link text and gave me the error "Button cannot contain emojis."

My temporary fix is to untick 'Allow custom link text' and have another field 'plain text' which does allow emojis. Would be better to have it as one field rather than two.

**Comment by sebastian-lenz** [comment]
Hm, the error is not triggered by this plugin but somewhere down the line. We don't support 4 byte characters as most of the databases cannot handle them correctly. I've added a converter for future versions that will pack / unpack 4 byte characters.
