### ISSUE TITLE
Bug: can't fetch entry titles

### ISSUE THREAD

**Issue by KatieMFritz** [sebastian-lenz/craft-linkfield#212]
When an entry is selected and there's no override text, I'm getting this error:

> Return value of lenz\linkfield\models\element\ElementLink::getIntrinsicText() must be of the type string, null returned

It points to [this line](https://github.com/sebastian-lenz/craft-linkfield/blob/204355ef53c0fbc0cd9699c544eb96a30a6390bc/src/models/element/ElementLink.php#L92).

If I uncheck "Enable element url and title cache" in the field settings, then it works.

**Comment by sebastian-lenz** [comment]
Hm, that's interesting. Do you have entry types where the title field is disabled? I've added a check to ensure we don't return `null` here.
