### ISSUE TITLE
Migration throwing error

### ISSUE THREAD

**Issue by bhashkar007** [sebastian-lenz/craft-linkfield#213]
I am updating "Typed Link Field" to the latest version 2.0.0-rc.2 but migration `m190417_202153_migrateDataToTable` is throwing error `PHP Warning 'yii\base\ErrorException' with message 'Error while sending QUERY packet. PID=71738'`. Even, I changed `max_allowed_packet` to `256MB` in MySQL config. Please help.

I am using:
Craft CMS v3.7.37
PHP v7.3.29

**Comment by sebastian-lenz** [comment]
A new version has been released that contains a fix for this issue.
