### ISSUE TITLE
Craft 4: Default link type not set correctly (from within matrix)

### ISSUE THREAD

**Issue by Antimated** [sebastian-lenz/craft-linkfield#221]
Heya! 👋

I have a matrix with (currently) 2 block types. One of the fields inside these blocks is a typed link field. Here I have set the "Default link type" to "Custom" but it doesn't seem like this setting is being respected.

**Screenshot of my matrix settings**
![Screenshot 2022-05-09 at 13 32 21](https://user-images.githubusercontent.com/2869409/167401400-908b2547-a0ef-4060-9312-fd4320619773.png)

**Screenshot of a newly created entry after I selected the matrix block type "Full"**
![Screenshot 2022-05-09 at 13 32 49](https://user-images.githubusercontent.com/2869409/167401465-286857b9-4abf-4a86-9f19-43da0deef657.png)

I would expect the typed link field to show me settings for the "Custom" link type.
I'm not sure if this is caused by using the link field inside of a matrix, or if it's just a more widespread bug.

**Plugin info**
- Typed Link field: 2.1.3-rc
- Craftcms: 4.0.1

**Comment by Antimated** [comment]
Any updates on this issue? Also when you select the "Default link type" there is no option to select "(no link)". I for one don't like the "(no link)" option to be displayed on the front-end at all.

**Comment by sebastian-lenz** [comment]
@Antimated I don't know, did you create a PR to fix your problem?

**Comment by Antimated** [comment]
> @Antimated I don't know, did you create a PR to fix your problem?

No I just opened this issue and was wondering if you looked into it or not. 😕

**Comment by WHITE-developer** [comment]
I have mixed feelings about this change. 
As long as the field isn't required I don't like it that it shows all the fields and so taking up space. Once the field is set to required I believe it already worked fine.
I would like to also haven an "(no link)" option in combination with this new behavior.
