### ISSUE TITLE
Make it possible to add attributes (classes/id's/data-attributes)...

### ISSUE THREAD

**Issue by jan-dh** [sebastian-lenz/craft-linkfield#222]
Would really love to see the option to add extra attributes. Sometimes you need authors to be abel to add extra stuff to a link (for tracking for example). Right now the only way for me to do that is to create a separate field for each link I need this on.

**Comment by chrisrowe** [comment]
+1 on this, we'd love to have a "display" dropdown for "button", "alternative", "inline" etc.

**Comment by sebastian-lenz** [comment]
Well, creating the additional required fields next to the link field is the Craft way of handling this, I see absolutely no point against it. The link field offers template helpers that allow you to easily render those fields together. Only a few users will need those fields and, as you may already note right here, there are users that want free text fields whilst others would prefer a dropdown. And, last but not least, each additional functionality we build into this plugin must be maintained and causes a lot of of work in the long run.

**Comment by chrisrowe** [comment]
Thanks @sebastian-lenz that makes sense. I guess in an ideal world we’re looking to encapsulate all potential attributes to a html anchor tag into one field. I can see the additional overhead this would create though.

Would you perhaps be open to providing an API/event to allow us to add this functionality  in the same way you do for custom Element Types?

**Comment by sebastian-lenz** [comment]
I don't see a way to expose a functionality like this using a simple/single event, adding fields to the link requires updating the cp template and all of the loading and saving functionality. Ideally you also want to hook into some of the output functions as well.

It's doable, I guess we would need something like a `ExtendedAttributes` model that comes with all of this functionality build in and the developer would have to replace this with his own custom subclass. But that's a lot of refactoring required here.

**Comment by jan-dh** [comment]
There are arguments to be made against having a seperate field next to every link. You'd have to make a lot of extra text input fields if you have some links around, which again would be very hard to maintain and the author experience is not very optimal, since you can't really visually "combine" them
