### ISSUE TITLE
Unable to click on "Open in new window ?" when inside a Super Table

### ISSUE THREAD

**Issue by billmn** [sebastian-lenz/craft-linkfield#227]
I have added a Types Link field inside a Super Table and I notice that the "Open in new window ?" cannot be checked.
It works fine outside Super Table fields.

Thoughts?

**Plugin info**
- Link field 2.1.3-rc
- Craft CMS 4.0.2

**Comment by DowleyDeveloped** [comment]
Seems like `Open in new window` always returns `NULL` even when checked in the newest version

**Comment by sebastian-lenz** [comment]
I've just tried to reproduce this and with the current version of Super Table and Link Field this works as expected. The option of the field "Open in new window?" is correctly saved and the links in the frontend receive the attribute "target" when selected.

@billmn Does the issues still exist for you? Could you provide more detailed steps to reproduce the issue? 

@DowleyDeveloped I don't understand your comment. What du you mean by "Open in new window" always returns "NULL"? Do you mean the helper `getTarget` on link models? This on should return `NULL` or `_blank` depending on user input.

**Comment by billmn** [comment]
@sebastian-lenz Nope, it doesn't work. I cannot check "Open in new window ?"

This is the structure of my field:
```
"menuFooter" (Super Table field)
    -> "sectionTitle" (Plain text field)
    -> "items" (Matrix field)
        -> "menuTitle (Matrix Block)
        -> "target" (Matrix Block)
            -> "target" (Link field)
```

**Comment by michaelhue** [comment]
I have the same issue when inside a Globals field.

Setting the `checked` attribute via DevTools will correctly save the value. But clicking anywhere on the checkbox will not check/uncheck it.
