### ISSUE TITLE
[2.1.3-rc] Asset volume source selection not working

### ISSUE THREAD

**Issue by WHITE-developer** [sebastian-lenz/craft-linkfield#229]
When limiting a link field to a specific asset source, you can't select any assets and are getting just a blank popup.
In the project config files you can see the sources you selected but when you edit the field the asset sources selection is empty again.
When selecting the `All` option for the asset sources it is working like it should

**Comment by twitcher07** [comment]
I can confirm this is happening to me on version 2.1.3-rc of the plugin and in Craft 4.0.4.

**Comment by simonkuran** [comment]
Same issue for me with the same Craft and plugin versions.

**Comment by mihob** [comment]
Same issue here, any news on this?

**Comment by sebastian-lenz** [comment]
Craft 4 changed the handling of assets sources, the plugin must be updated to handle the new source definitions in Craft 4.

**Comment by simonkuran** [comment]
Thanks for fixing this! Is there an ETA for this to be released to the plugin store for updating?
