### ISSUE TITLE
Consolidate to two rows

### ISSUE THREAD

**Issue by chasegiunta** [sebastian-lenz/craft-linkfield#23]
I think Linkfield takes up one too many rows. It's really noticeable upon placing into other fields like Matrix or SuperTable. Could we reduce as much margin between fields as possible & reduce it to two rows?

"Open link in new window?" and relationship/url input fields could really go into the same row.

**Comment by sebastian-lenz** [comment]
Maybe we could introduce something like a "compact mode" where we try to place the fields in on line? Cause outside of a matrix/table field I'm fine with the layout.

**Comment by chasegiunta** [comment]
Maybe! There's _another popular link plugin_ that handles this fairly well, but I'll ask this way: Is there anything to be gained by having the custom link text field take up the whole row? (asking for desktop views, I can understand mobile) 

I'd argue that a 600px input field isn't necessarily in the majority of cases - and theoretically this truncation would only be an issue if both 'Allow custom link text' & 'Allow links to open in new window' are checked.
