### ISSUE TITLE
Anchor link type 

### ISSUE THREAD

**Issue by JorgeAnzola** [sebastian-lenz/craft-linkfield#236]
I don't know if it really makes sense, but I've added an [achor type](https://github.com/JorgeAnzola/craft-linkfield/blob/master/src/models/InputLinkType.php#L187) just so the user doesn't need to enter "#url".  Probably not even worth creating a pull request, I just needed that for my use case. 

Thanks for the great plugin!

**Comment by sebastian-lenz** [comment]
We already have a lot of different link types in core, I'm a bit cautious about adding another one. For this exact scenario we have added the possibility to disable the validation of url types.
