### ISSUE TITLE
Get children of a linked entry/structure

### ISSUE THREAD

**Issue by hendrikeng** [sebastian-lenz/craft-linkfield#24]
I am trying to achieve a multi level navigation with the use of  `craft-linkfield`.

E.g. I do use `craft-linkfield` to create my site navigation and simply link to a entry or category. 
However for a specific site i need to create a multilevel menu that would create links for the children of an entry, is it even possible to get the children of an entry through `craft-linkfield`.

Thanks for the awesome work!

**Comment by sebastian-lenz** [comment]
You can access the linked entry in our templates using the ˋgetElementˋ method of the link field. This method returns the complete entry allowing you to access its properties and e.g. children as usual. The method will return ˋnullˋ if no link or a text link is set, so make sure to check for that in your template by using the ˋhasElementˋ method beforehand.

ˋˋˋ
{% if entry.myLinkField.hasElement %}
  {% foreach child in entry.myLinkField.element.children %}
    <a href="{{ child.url }}">{{ child.title }}</a>
  {% endfor %}
{% endif %}
ˋˋˋ

**Comment by hendrikeng** [comment]
thanks a lot @sebastian-lenz
