### ISSUE TITLE
No way to query a disabled element in the linkField query in GraphQL

### ISSUE THREAD

**Issue by toddpadwick** [sebastian-lenz/craft-linkfield#240]
We have some entries in the navigation which are disabled until ready until the product launches. Although we won't include the URL until they are enabled, we do still want to display the title, linkText and an icon which is pulled in via the LinkField `element` object. However, when the entry is disabled, the element is returned empty. I'd expect the following to be allowed, just like it is in Craft's default entry query:
```
  navLink {
    target
    text
    element(status:["live","disabled"]) {
        id
        title
        uri
        slug
        ... on hardware_hardware_Entry {
          summary
          headline
          tags
          icon {
            url@transform(width:96)
            uri
            srcset(sizes:["36","48","72", "96"])
            id
            title
            width
            height
            extension
          }
        }
      }
  }
```

However the above returns a GQL error.

**Comment by sebastian-lenz** [comment]
The field `element` does not return a query, so you cannot to pass any arguments right there.
