### ISSUE TITLE
Link from another website with restricted rights

### ISSUE THREAD

**Issue by yingban** [sebastian-lenz/craft-linkfield#249]
Hi,

I would like to confirm a feature from my tests with v2.1.5.
I am working on a multisite (site A and site B), with 2 user groups (group A and group B), and respectively user A who can only edit site A, and user B who can edit only site B.

I have matrix link field which allows to link with Entry types and "Allow links to reference a different site" checked.
If user B cannot edit the "site A", in the modal the dropdown will not show "site A", but should he be able to at least "view" the list of entries, without being able to create an entry in site A?

If I allow user B to edit site A, then he will be able to link with entries from a different site.
Thanks for helping.

**Comment by sebastian-lenz** [comment]
I am honestly not sure what the correct behavior should be here. But basically this plugin hands of that functionality to the element select dialog that is part of the Craft CMS. What happens if you create an entry field that allows users to select entries from those uneditable sites?

**Comment by yingban** [comment]
It will not be visible, unless the option is "Show entries from this website".

But my issue is solved somehow, I convinced the PM that the client could always use the URL type, and paste an URL of page from a website they don't have access to.
