### ISSUE TITLE
Calling unknown method: lenz\linkfield\fields\LinkField::factoryTypeHint()

### ISSUE THREAD

**Issue by bleepsandblops** [sebastian-lenz/craft-linkfield#252]
Getting this error on a new site when creating a new link field:
`Calling unknown method: lenz\linkfield\fields\LinkField::factoryTypeHint() in "__string_template__2feea56560234f273691feaa93ef7d61" at line 7

Application Info
PHP version	8.1.13
OS version	Linux 5.10.104-linuxkit
Database driver & version	MySQL 10.3.37
Image driver & version	Imagick 3.7.0 (ImageMagick 6.9.11-60)
Craft edition & version	Craft Pro 4.3.6.1
Yii version	2.0.47
Twig version	v3.4.3
Guzzle version	7.5.0
Plugins
Craft Commerce	4.2.4
Empty Coalesce	4.0.0
Pest	1.0.0-alpha11
Redactor	3.0.3
Redactor Tweaks	3.0.0
SEOMate	2.0.3
Servd Assets and Helpers	3.2.4
Super Table	3.0.7
Typed link field	2.1.5
Vite	4.0.4

**Comment by bleepsandblops** [comment]
Looks like it's something to do with the Pest plugin! https://github.com/markhuot/craft-pest

**Comment by sebastian-lenz** [comment]
The update that should fix this is finally online and this issue should be resolved after running `composer update`.
