### ISSUE TITLE
LinkedTitle returns null after updating craft and linkfield plugin

### ISSUE THREAD

**Issue by jornwildenbeest** [sebastian-lenz/craft-linkfield#259]
After updating Craft 3.7.67 and Craft-linkfield 2.0.0-rc.2 I get the following error:

```
Return value of lenz\\linkfield\\models\\element\\ElementLink::getIntrinsicText() must be of the type string, null returned

"file": "/Users/jorn/Sites/vanwijknieuwegein-backend/vendor/sebastianlenz/linkfield/src/models/element/ElementLink.php",
      "line": 92,
      "trace": [
        {
          "file": "/Users/jorn/Sites/vanwijknieuwegein-backend/vendor/sebastianlenz/linkfield/src/models/Link.php",
          "line": 323,
          "call": "lenz\\linkfield\\models\\element\\ElementLink::getIntrinsicText()"
        },
        {
```

After saving the entry again through the control panel, it does work again. But saving the entries through `./craft resave/entries` does not work.

This can be fixed by changing the code in ElementLink.php to:

```
if ($this->_field->enableElementCache) {
      return $this->linkedTitle ?? "";
    }
```

If I submit a PR, would you accept this? @sebastian-lenz

**Comment by sebastian-lenz** [comment]
Hi, sure I would accept that PR. But the code actually already looks like this in the current version:
https://github.com/sebastian-lenz/craft-linkfield/blob/main/src/models/element/ElementLink.php#L92

**Comment by bartdigitalpulse** [comment]
I'm seeing this issue show up as wel on a project. I'm confused, you say the code looks already like this but it doesn't? 

https://github.com/sebastian-lenz/craft-linkfield/blob/main/src/models/element/ElementLink.php#L92

@sebastian-lenz
