### ISSUE TITLE
Adding relative links

### ISSUE THREAD

**Issue by dgrigg** [sebastian-lenz/craft-linkfield#26]
Is there a way to add a relative link to a linkfield, ie /product/test instead of http://mysite.com/product/test? Right now any relative url is rejected. It would also be nice to add a token like {siteUrl}/product/test that would replace the siteUrl with the current domain being used.

**Comment by sebastian-lenz** [comment]
You can allow relative links in custom url fields by disabling the validator in the options of the field. The idea with the tokens is great, I'll have to check which APIs the Craft/YII has to offer.

**Comment by dgrigg** [comment]
perfect, thanks

**Comment by sebastian-lenz** [comment]
Note: we just received (and accepted) a pull request that will add new field type to the url field that has no validation by default, see https://github.com/sebastian-lenz/craft-linkfield/pull/28. So with the next version you'll also receive a field that accepts relative urls out of the box.
