### ISSUE TITLE
Declaration PHP Compile Error after Craft 3 => 4 upgrade

### ISSUE THREAD

**Issue by sander-lameco** [sebastian-lenz/craft-linkfield#270]
So the error we're getting whenever we try to enter the CP:

```
Declaration of modules\craftutilitiesmodule\models\element\FormLinkType::rules() must be compatible with lenz\linkfield\models\LinkType::rules(): array
```

The upgrade and migrations where successful so I'm not sure was seems to be causing the problem here.

Versions: 
- Craft CMS: `4.5.2`
- Typed Link Field: `2.1.5`
- PHP: `8.2`

If you require more information I can provide more.

Also opened a ticket over at Craft CMS https://github.com/sebastian-lenz/craft-linkfield/issues/270 if this is Craft related.

**Comment by sander-lameco** [comment]
Issue can be closed since I found the issue. 
This is a project we took over from another agency and they had a custom module which didn't match with the requirements after the update.

**Comment by sebastian-lenz** [comment]
Okay, great, thanks for the update!
