### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by mfell** [sebastian-lenz/craft-linkfield#282]
Hi Sebastian,

just asked very carefully: Do you planning an update for Craft 5?
That ould be verrry kind. :)

Thanks a lot for you work and support, of course!

Greetz Marc

**Comment by sebastian-lenz** [comment]
No, this plugin will not be available for Craft 5.

**Comment by lindseydiloreto** [comment]
To request this feature be added to Craft core, see https://github.com/craftcms/cms/discussions/9062 ▶️
