### ISSUE TITLE
Craft 5 

### ISSUE THREAD

**Issue by stephanedemotte** [sebastian-lenz/craft-linkfield#283]
Linkfield is one of the most used plugin in Craft and is no more maintained.

Maybe a team like @nystudio107 or @spicywebau can take the relay and make it work on craft 5 ? 

It's my 2 cents.

Thank

**Comment by sebastian-lenz** [comment]
Please see the discussion here:
https://github.com/sebastian-lenz/craft-linkfield/discussions/281
