### ISSUE TITLE
More compact display

### ISSUE THREAD

**Issue by lazlo-bonin** [sebastian-lenz/craft-linkfield#29]
I'm really enjoying LinkField, but I think it's taking a bit too much space in my field list for an entry, especially for big entries.

Here are screenshots of what I mean:
https://imgur.com/a/y3PlA2I

I achieved the second result by changing some styling in Chrome, and I'll probably do it permanently through a CP CSS plugin, but it'd be great to have this built in I think!

**Comment by lazlo-bonin** [comment]
Here's the CSS I added in case anyone's interested:

```
.linkfield.withSettings {
    display: flex;
    align-items: center;
    padding: 0;
    border: none;
}

.linkfield--field {
 	margin: 0;   
}

.linkfield--settings {
    flex-shrink: 0;
    margin-left: 1em;
}
```

**Comment by sebastian-lenz** [comment]
Okay, next version will display in one line if only the new window option is selected.
