### ISSUE TITLE
GraphQL: use element field, instead of each

### ISSUE THREAD

**Issue by timkelty** [sebastian-lenz/craft-linkfield#31]
Right now the element field gets added its named type, `entry`, `asset`, `category`, etc.

I think it would be more usable to always add it as `element`.
So a query might look like:

```
linkField {
        url
        element {
            id
            ...on EntryInterface {
                title
             }
            ...on CategoryInterface {
                title
            }
        }
}
```

**Comment by sebastian-lenz** [comment]
If this is more conveniant for GraphQL users then sure, lets do it like that. Again it would be nice if we could offer both right now and mark the old ones as being deprecated.

**Comment by sebastian-lenz** [comment]
The current GraphQL version seems to be broken. Is this correct?
https://github.com/sebastian-lenz/craft-linkfield/blob/master/src/utilities/CraftQLListener.php#L88

**Comment by timkelty** [comment]
I think that's the right idea, but either I don't get how `markhuot\CraftQL\Builders\InterfaceBuilder\ElementInterface` is supposed to be used, or its broken…

I just started familiarizing myself with the CrafQL codebase this week, and this is actually something I'm not totally sure how to achieve.

Essentially we want to add a field that can resolve to several types (entry, category), preferably with a base type (element).

Maybe @markhuot can chime in?

**Comment by sebastian-lenz** [comment]
I'll close this for now. CraftQL seems to be pretty inactive lately, so I doubt we'll see big improvements there in the near future. Furthermore, Craft 3.3 is rumored to launch with an [official GraphQL API](https://github.com/craftcms/cms/pull/4540) so from the perspective of this plugin, it makes sense to wait for that to be implemented and then check back onto GraphQL improvements.
