### ISSUE TITLE
Tel Link

### ISSUE THREAD

**Issue by laurabennett** [sebastian-lenz/craft-linkfield#32]
It would be great to allow for telephone formatting for instance (xxx) xxx-xxxx so that users are only entering numbers where the x's are in the back end and then I can reformat how I want on the front end.  Currently the value is also stored with "tel:" which is helpful for the url portion but not how I want the number to display.

Thanks!

**Comment by sebastian-lenz** [comment]
Forcing a certain input format for phone numbers is quite complicated. There is the obvious problem of no native html elements supporting something like this, so we would have to tackle it with some kind of js component. Additionally the preferred format for phone numbers differs from country to country.

To me the current, simple solution seems to be the best way to go in the context of a field that is mainly intended to be used to author links e.g. in a menu or footer. If you need to collect phone numbers in a fixed format, there my be other fields / plugins that better suit your needs.

You can access the raw user input using the `value` property of the link model, this does not contain the prefix `tel:`.
