### ISSUE TITLE
Ability to choose the entry type in a structure

### ISSUE THREAD

**Issue by janhendrickx** [sebastian-lenz/craft-linkfield#33]
A feature request: 
Wouldn't it be handy to be able to select a specific entry type in a structure? So if you choose a structure, you get the entry types to select from too? Or something like that? I'd love to see that happen - I've bumped into a problem in the past (and now) in which that possibility would've saves me quite a lot of work.

**Comment by janhendrickx** [comment]
Yeah, something like that would work. 
ATM I'm working on a site for a client that has a section which has 2 entry types. Now I'm building a matrix field in which the client can only choose 1 of those 2 entry types. This is because those 2 entry types only have one different, but very important field. And our client should only be given the possibility to choose en entry from that one entry.type since I need to show that one specific field in that matrix block. I'm still surprised that it still isn't a native feature in Craft itself, so I hope your plugin will makes this able (that way I can get the content of the selected entry via your linkField). It happened to me a few times before, so I would love to see that feature :-)

**Comment by sebastian-lenz** [comment]
Okay, the `criteria` is passed on to the underlying `ElementQuery` (https://github.com/craftcms/cms/blob/develop/src/elements/db/ElementQuery.php) of the displayed tree, but I don't see now criteria to filter by an entry type.

**Comment by jsunsawyer** [comment]
@sebastian-lenz Here's a plugin that I use to handle this for entry fields themselves.

https://github.com/nfourtythree/craft3-entriessubset

**Comment by sebastian-lenz** [comment]
I'll close this issue due to inactivity. I've decided to collect all feature requests in a markdown document, see https://github.com/sebastian-lenz/craft-linkfield/blob/master/WISHLIST.md
