### ISSUE TITLE
Linking to pending entries

### ISSUE THREAD

**Issue by chrisrowe** [sebastian-lenz/craft-linkfield#35]
I've discovered getElement returns null when the linked entry is pending, I feel like I should at least be able to pass `status(null)` or similar to get at it. Is this something I can't figure out or is this not yet supported?

**Comment by chrisrowe** [comment]
It's a calendar, where I'm using postDate as the event date, I'm reworking this anyway to have a separate field but I feel like I should still be able to access all entries with a status parameter as per `craft.entries`

**Comment by sebastian-lenz** [comment]
The `getElement` and `hasElement` methods of the link model now accept a parameter "ignoreStatus". When set to `true` those methods will return unpublished elements.

**Comment by chrisrowe** [comment]
Thank you! 💯
