### ISSUE TITLE
Using conditionals with link properties

### ISSUE THREAD

**Issue by jayhlee** [sebastian-lenz/craft-linkfield#39]
Is there a way to use a conditional on a property of a link? For example, I'd like to first check if the `getTarget()` is defined and do something like this:

```
{% if item.myLinkField.getTarget() | length %}
target="{{ item.myLinkField.getTarget() }}"
{% endif %}
```
This way, I don't need to have my target output empty (like this `target=""`) when it's not defined.

**Comment by sebastian-lenz** [comment]
Yes, the link behaves like a normal model within a twig template so you can use all the tools twig has to offer on the link fields.

Please note that `getTarget()` will return `NULL` if no target is set, therefore you should be able to simple check it like this:
```
{% if item.myLinkField.target %}
  target="{{ item.myLinkField.target }}"
{% endif %}
```
