### ISSUE TITLE
Choosing default link type

### ISSUE THREAD

**Issue by onebrightlight** [sebastian-lenz/craft-linkfield#4]
Currently the plugin displays the first activated link type when the field type is used. This could be improved by allowing the user to choose the default link type, instead.

## Use case example

I am creating a navigation builder using Craft’s Structure section type. 9 times out of 10 I will want to use an entries link, but there are times where the client will want to include a link to an external site, too. It would be helpful if the fieldtype allowed me to just default to the entry link instead.

**Comment by ockam** [comment]
+1

**Comment by sebastian-lenz** [comment]
Yes, this behaviour annoys me too. I'll add a simple dropdown that allows selecting the default link type.

**Comment by sebastian-lenz** [comment]
I've added this feature in v1.0.4 so I'll close this issue for now. If there are any problems remaining, please let me now!
