### ISSUE TITLE
Feature Request: getAttrs

### ISSUE THREAD

**Issue by glitchedmob** [sebastian-lenz/craft-linkfield#41]
Right now when using the field in templates there are methods for grabbing each of the available fields, which is great. But I'm wondering if we could maybe have a shortcut method to get all of them at once. 

The biggest thing this would help with is the scenario where you need the anchor tag to wrap some other elements. You can grab all of the fields one by one, but it can get a little verbose. For example

```
<a
    class="nav-link"
    href="{{ entry.customLink }}"
    {% if entry.customLink.getTarget %}
        target="{{ entry.customLink.getTarget }}"
    {% endif %}
    {% if entry.customLink.getTitle %}
        title="{{ entry.customLink.getTitle }}"
    {% endif %}
    {% if entry.customLink.getAriaLabel %}
        aria-label="{{ entry.customLink.getAriaLabel }}"
    {% endif %}
>
    <p>
        {{ entry.customLink.getText }}
    </p>
</a>
```

But I'm thinking this logic could be extracted into a `getAttrs` method that would behave something like

```
<a {{ entry.customLink.getAttrs }}>
    <p>
        {{ entry.customLink.getText }}
    </p>
</a>
```

If this feature sounds like it would be a good fit to add to this plugin, I'm totally willing to jump in and submit a PR for it. I just wanted to run the idea past everyone first and potentially get some feedback before jumping straight into code.

**Comment by sebastian-lenz** [comment]
Hi and thanks for your suggestion! As I think this makes sense, I extracted the attribute logic of the `getLink` helper to a second method called `getLinkAttributes`. It returns an associative array now which I would prefer from an API standpoint, can this be easily rendered inside twig templates?

**Comment by glitchedmob** [comment]
Although it doesn't provide that API I was suggesting in the original issue, I think this could work pretty well. Users could actually use twig to pull off that original API using macros. 

```
{% macro attrs(linkAttributes) %}
    {% set attrs = '' %}
    {% if linkAttributes['href'] %}
        {% set attrs = attrs ~ 'href="' ~ linkAttributes['href'] ~ '" ' %}
    {% endif %}
    {% if linkAttributes['target'] %}
        {% set attrs = attrs ~ 'target="' ~ linkAttributes['target'] ~ '" ' %}
    {% endif %}
    {% if linkAttributes['title'] %}
        {% set attrs = attrs ~ 'title="' ~ linkAttributes['title'] ~ '" ' %}
    {% endif %}
    {% if linkAttributes['aria-label'] %}
        {% set attrs = attrs ~ 'aria-label="' ~ linkAttributes['aria-label'] ~ '" ' %}
    {% endif %}
    {{ attrs }}
{% endmacro %}
```

Side note: I'm just assuming that `object['property']` style is how associative array access works in twig (I haven't tried it)

Using that macro would look something like this.

```
{% import 'linkHelpers.html' as linkHelpers %}

<a {{ linkHelpers.attrs(entry.customLink.getLinkAttributes) }}>
    <p></p>
</a>
```

Do you think it would be helpful to add something like this to the docs as a suggestion?

**Comment by sebastian-lenz** [comment]
New version is out containing `getLinkAttributes`.
