### ISSUE TITLE
Invalid Call on Entry Save

### ISSUE THREAD

**Issue by DaBlackBeerd** [sebastian-lenz/craft-linkfield#42]
I'm getting the following error whenever saving an entry that has a linkfield field:

`Setting read-only property: typedlinkfield\models\Link::url`

### Additional Information: 
Craft CMS 3.0.17.1
Typed link field 1.0.14
PHP 7.0.22

**Comment by sebastian-lenz** [comment]
Hi and thank you for the report! Unfortunately I cannot reproduce this issue in my development version. Do you have a stack trace of the error you could send me to tackle down that error?

**Comment by sebastian-lenz** [comment]
This is really strange, somehow the property `url` is in the raw model data but we don't have (and never had it) on our model. I am actually a bit afraid that there is actually wrong data pushed to the link model. I've resolved this issue by filtering the input data that goes into the link model.

**Comment by sebastian-lenz** [comment]
A new version has been released that should fix this problem.
