### ISSUE TITLE
Include rel="noopener noreferrer" for target="_blank" attribute

### ISSUE THREAD

**Issue by terryupton** [sebastian-lenz/craft-linkfield#43]
Suggest that when using `{{ entry.singleLink.getLinkAttributes() }}` and the link is set to `target="_blank"` that the `rel="noopener noreferrer"` is included by default inline with best practices around security and performance.

**Comment by sebastian-lenz** [comment]
Hi, thank you for your suggestion. Sounds reasonable. Do you think we should always set them or might it be usefull to make this behaviour configurable?

**Comment by terryupton** [comment]
Yeah perhaps as a configurable option when you select the option to open in a new window.
I think it can have some conflict with referrer tracking and some affiliate links. Although lost referrer tracking should only be an issue if you have a non-secure http connection in the mix.

A few links I found if you want to explore more...
https://support.performancefoundry.com/article/186-noopener-noreferrer-on-my-links
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/https://stackoverflow.com/questions/50709625/link-with-target-blank-and-rel-noopener-noreferrer-still-vulnerable

**Comment by JayBox325** [comment]
Just chiming in, I think that if the user selects the link to be opening in a new tab, we should always add the requested props mentioned above. I haven't come across an instance where I wouldn't include them in a new window link. But I could be wrong.

Besides, it'd be one less option to check every time I use this great field type.

Cheers
