### ISSUE TITLE
Remove site dependency on element select field

### ISSUE THREAD

**Issue by monachilada** [sebastian-lenz/craft-linkfield#44]
Would you consider removing the hardcoded relation criteria to elements within the current site, to enable selecting elements across sites?

Looking into the code, it appears even if this were to be accepted, it would require a change in core that would allow the `_includes/forms/elementSelect` macro to respect the `showSiteMenu` setting in the `Craft.BaseElementSelectInput` JS function.

I've filed a pull request for that anyway, as it seems like an oversight: https://github.com/craftcms/cms/pull/3494. If this were to be accepted it would pave the way to implementing something like this in the plugin.

**Comment by sebastian-lenz** [comment]
Hi and thank you for sour suggestion. Sounds like a good idea, I'll have an eye on your Craft issue.

**Comment by sebastian-lenz** [comment]
Well, if I understand your problem correctly we also would have to store the id of the site the user has selected? That's also what Brandon Kelly mentioned in the other issue.

**Comment by monachilada** [comment]
You're right. I just played around on a local fork and it would indeed have to store a reference to the `siteId`. I got stuck on what to do next at that point though, it's outside of my understanding of the plugin (and plugins) in general on where that type of thing would be stored.

**Comment by sebastian-lenz** [comment]
Yeah, I will have to take a look at this. The element selection currently only stores an integer as this is all what's needed to refer to another element. In this case we must store a small structure but obviously we don't want to break existing installations.

I also want to add the ability to add custom queries and fragments to those element urls (as I just stumbled upon this problem in a current project)and this functionality also requires the ability to store extra data along the element id. Once we have this, storing the site id should be easy.

**Comment by monachilada** [comment]
That's great. Let me know if you want help testing or anything like that.

**Comment by sebastian-lenz** [comment]
This feature is part of the 2.0 release.
