### ISSUE TITLE
Default Text value not used as fallback

### ISSUE THREAD

**Issue by jsunsawyer** [sebastian-lenz/craft-linkfield#45]
My expectation is that the `Default link text` should display if no `Custom link text` is provided by the user. Instead, `Learn More` is returned.

**Comment by sebastian-lenz** [comment]
Hi, thank you for reporting this. Sounds like a clear bug too me.

**Comment by jsunsawyer** [comment]
Using `entry.element.customText` instead of `entry.element.getCustomText()` returns the placeholder text fallback correctly.

**Comment by walshmichael** [comment]
Can confirm. Using `entry.element.getCustomText('My fallback title')` returns the `Default link text` when it is an empty string and the fallback when the default is not empty.

Looks like the ternary operator on Line 335 of `/src/models/Link.php` is the wrong way around.

`return empty($defaultText) ? $defaultText : $fallbackText;`

Thanks.
