### ISSUE TITLE
Feature Request: Add ability to define reusable field settings

### ISSUE THREAD

**Issue by jsunsawyer** [sebastian-lenz/craft-linkfield#47]
We often use entry types to handle data to help with content translations, define reusable content blocks, set scheduled announcements, etc.

Link fields need to have these removed, so the user is only presented with entries that they should be linking to.

As soon as we uncheck `all` (from Categories, Entries, etc) and define our available sources, we end up with a project management nightmare. The next time a new entry type is added, we have to remember to go into every field, sometimes deeply nested in Matrix or Super Tables, and ensure that we add that type as an available source.

Outside of handling sources, being able to define our other options would also be a welcome improvement. Currently, every time I add a new link field, I have to go through the whole setup process again.

If we could define all of our unique link types in a settings panel, then optionally select from them when creating a link field (much like related entries), this would greatly reduce the chance for errors and save us a lot of hassle.

**Comment by jsunsawyer** [comment]
Something similar to redactor config files _could_ work. The thing about having this be part of the backend is that we'd have visibility of all of our asset sources, categories, entries, etc. It might become too cumbersome to manage via config files.

**Comment by sebastian-lenz** [comment]
I'll close this issue due to inactivity. I've decided to collect all feature requests in a markdown document, see https://github.com/sebastian-lenz/craft-linkfield/blob/master/WISHLIST.md
