### ISSUE TITLE
Allow localized custom link text

### ISSUE THREAD

**Issue by exophunk** [sebastian-lenz/craft-linkfield#48]
Is it possible that you can add a setting so we can specify if the "Custom link text" should be specific to site/languages?

I know I can set the whole field to «Translateable», but I actually don't want customers to add different links in every language, but simply add a different Link text.

So for example if you add a Link with the Text «Read more», you should be able to add a localized Link Text like «Mehr lesen» in german, without localizing the whole field and the link itself.

Thank you!

**Comment by sebastian-lenz** [comment]
Hm, sounds like you want to fields, one field for the link that is not translated and one field for the caption that is translated? As the translation stuff is handled by the Craft CMS field system on a per field basis the cleanest way would be to actually use two separate fields for that. I'm not very attracted to the idea of replicating the logic of the core CMS within this plugin.
