### ISSUE TITLE
Settings are lost on 3.1

### ISSUE THREAD

**Issue by timkelty** [sebastian-lenz/craft-linkfield#49]
Any section/category type field settings seem to be lost after a 3.1 upgrade.

Inspecting the HTML source on the field settings page, it would seem it is now expecting a UID, not an ID.

Not sure, but maybe related to this line from the 3.1 release notes:

> System user permissions now reference things by their UIDs rather than IDs (e.g. editEntries:<UID> rather than editEntries:<ID>).

Seems problematic, and probably not just isolated to this plugin.

**Comment by timkelty** [comment]
This seems to be the offending commit, changing the `key` of Element's sources to be UIDs: https://github.com/craftcms/cms/commit/4f5a9e3b212c5d997f7929d2cdc2b9097350a5ae

**Comment by sebastian-lenz** [comment]
Hi, thank you for reporting this. Indeed, it seems like the Craft core has changed the formatting of the `key` property of the element sources array as obtained by `craft\base\ElementInterface::sources()`. Before it contained the id of the entry type and was something like 

```
section:8
```

After the update to Craft 3.1.* the key is a string containing the uid like 

```
section:a10ef3a4-0b28-4831-b6b6-195167b87212
```

Therefore all field settings of the link field saved before the 3.1 update become invalid and have to be reconfigured.

**Comment by sebastian-lenz** [comment]
Okay, I've added a simple validator to rewrite the settings on load. A new release is out containing the fix. However, if the field has been saved in Craft 3.1 the settings are already lost.
