### ISSUE TITLE
Get link type functionality

### ISSUE THREAD

**Issue by mortscode** [sebastian-lenz/craft-linkfield#52]
Hey @sebastian-lenz THANK YOU for this plugin. It's just what I need for my project.

Question: Is there a way to return the type of the field (entry, category, url, etc)? I'm not seeing it in the documentation and when I try `link.myLinkField.getType()` it errors out.

Sorry to ask a question in an issue, couldn't find you on Craft Slack.

**Comment by madebyspark** [comment]
Did you ever find a solution to this @mortscode ?

**Comment by mortscode** [comment]
nope @madebyspark

**Comment by madebyspark** [comment]
Thx @mortscode

**Comment by sebastian-lenz** [comment]
You can access the link type using the attribute `type` on the link model:
```
  {{ link.myLinkField.type }}
```

See: https://github.com/sebastian-lenz/craft-linkfield/blob/master/src/models/Link.php#L47
