### ISSUE TITLE
Facing some issues when previewing links with custom link text in a page saved as a Draft

### ISSUE THREAD

**Issue by harshaherath** [sebastian-lenz/craft-linkfield#53]
I’m facing some issues when previewing links with custom link text in a page saved as a Draft. Happens when I click Share button to preview. When I click on the Share button (next to Live Preview button), Instead of showing the custom text, it shows the default text. For Entry, it shows only the entry title. Please refer the attached images.

When click on Share button to preview changes:

<img width="1216" alt="screen shot 2019-02-14 at 12 47 03 pm" src="https://user-images.githubusercontent.com/11188434/52758667-1390f380-3059-11e9-915b-0891f3f38f72.png">
<img width="1205" alt="screen shot 2019-02-14 at 12 48 11 pm" src="https://user-images.githubusercontent.com/11188434/52758668-1390f380-3059-11e9-834a-346f84b64b03.png">

In Live Preview:

<img width="1592" alt="screen shot 2019-02-14 at 12 49 03 pm" src="https://user-images.githubusercontent.com/11188434/52758688-25729680-3059-11e9-88ae-03c07b5d2b77.png">
<img width="1599" alt="screen shot 2019-02-14 at 12 49 53 pm" src="https://user-images.githubusercontent.com/11188434/52758689-25729680-3059-11e9-9a65-e1f5fa8a9b74.png">

**Comment by thejoshsmith** [comment]
Can confirm this is also happening for me on Craft 3.1.8.

**Comment by harshaherath** [comment]
Hi, any updates on this?
