### ISSUE TITLE
Using a Global Link Field

### ISSUE THREAD

**Issue by mateostabio** [sebastian-lenz/craft-linkfield#58]
Hello, Is there an easy way to select Global link fields I have under Globals > links
I have them in globals because they are external links I use and reuse all around the site. ex.: in the header, footer, contact page, pricing page. So would be nice to only use one link that would change all around the site. 
I thought I'd be able to do something in the link field by using custom and entering for the URL {{ links.freeTrialLink }} and {{ links.freeTrialLink.getText() }} for the button text, but no luck :(

Is this something that might be of value to others?
Thanks for a great plugin, nonetheless.

**Comment by sebastian-lenz** [comment]
Hi! We already discussed this type of links in this issue: https://github.com/sebastian-lenz/craft-linkfield/issues/18. As globals do not have an url, selecting a global by itself does not resolve to a link. In your case it sounds like we would need to additionaly know which field on the global we should return.

How is your project setup? Do you use multiple globals with a link field on each or do you have a single global with multiple link fields?
