### ISSUE TITLE
Linking Entries to itself

### ISSUE THREAD

**Issue by LeoWie93** [sebastian-lenz/craft-linkfield#59]
For example editing the entry "Contact", i would like to add a link that points to the entry itself but with an additional anker. `/contact#anker`.

But the plugin greys out the entry you are currently editing.

Am i missing something in the settings?

**Comment by sebastian-lenz** [comment]
Hi! Yes, we send the current page id to the element select field as the origin and the element select field therefore grays out that entry in the select dialog. Usually this seems like the desired behavior as links to the current entry barely make sense. As a simple solution you could use the "custom" link type and just enter ``#anker`` as the link value.

**Comment by LeoWie93** [comment]
Using the "custom" link type and tweaking my code made it possible. Thanks for the tipp!

My thoughts:
Using the linkfield inside a matrix makes it possible to link to the current entry. In my opinion this defeats the reasoning to restrict linking to the current entry when its a single field.

**Comment by sebastian-lenz** [comment]
Seems fair, I have removed the restriction.
