### ISSUE TITLE
Issue with channels

### ISSUE THREAD

**Issue by mikegraham00** [sebastian-lenz/craft-linkfield#6]
When trying to select an entry, I'm not seeing any entries in Channel-type sections. Structures and singles seem to work fine.

I thought it might be an issue with multisite, but Channel-type section entries don't show up whether or not they are set to "propagate across all sites".

Thanks for the plugin!

**Comment by sebastian-lenz** [comment]
I can see entries in channels, I guess you are right and the issue arrises due to a multisite setup.

**Comment by sebastian-lenz** [comment]
I've added this feature in v1.0.4 so I'll close this issue for now. If there are any problems remaining, please let me now!
