### ISSUE TITLE
Content inside a "linkfield" is not accessible via Crafts `find()->relatedTo`

### ISSUE THREAD

**Issue by LeoWie93** [sebastian-lenz/craft-linkfield#60]
I, for example, have an entry "Contact" and it is linked on various other entries via the **linkfield** and **entries field**.

Now im trying to get all the entries the "Contact" entry is linked on via the following code:

```
return Entry::find()->relatedTo([
            'targetElement' => $contactEntryId,
            'field' => [
               'entriesCollection' , //<-- entries field
               'linkedfield', <-- linkfield
            ],
        ])->all();
```

Only using the `entriesCollection` i get all entries the "Contact" entry was linked inside a **entries field**.

Using it in combination or only the `campaignsiteCallToAction` i get no response. It should return all entries where the "Contact" entry was linked inside a **linkfield** and/or **entries field** 

I hope i explained my issue clearly. If not, im happy to explain further.

**Comment by sebastian-lenz** [comment]
Hi! Yes, this is by design, the link field does not store the linked elements as relations to the database. You cannot use the link field to query the linked elements, if you need this you should use one of the relation fields provided by Craft CMS.

**Comment by tremby** [comment]
Poking my head in to say that I was hoping for this feature. I have some cases where an entry type has a field which might be a link to an entry or it might be an external URL, and I'd really like this object to pop up in `relatedTo` queries if an entry was chosen. The only alternative I can see is to provide both a link field and a Craft relation field, and instruct the content author that they should prefer one over the other. This would also complicate my data layer and front end code.
