### ISSUE TITLE
"Please enter a valid URL" when the URL contains 80 characters or more (since v1.0.18)

### ISSUE THREAD

**Issue by benface** [sebastian-lenz/craft-linkfield#62]
It looks like [this PR](https://github.com/sebastian-lenz/craft-linkfield/pull/57) is the cause, because if I comment out that line (`$value = idn_to_ascii`...) it works fine. But when I keep it as is, any URL that is over 79 characters doesn't validate. Try with this URL for example (exactly 80 characters):

https://example.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by benface** [comment]
Related(?): https://bugs.php.net/bug.php?id=67084

**Comment by sebastian-lenz** [comment]
Hi, thanks for reporting this. I think we would be better off by switching to the url validator provided by Yii as it seems to offer a better functionality.

**Comment by sebastian-lenz** [comment]
I've just published a hotfix.

**Comment by benface** [comment]
Thank you!!
