### ISSUE TITLE
Empty fields are awkward

### ISSUE THREAD

**Issue by timkelty** [sebastian-lenz/craft-linkfield#63]
Often we have an optional LinkField, but that can appear awkward, as there is always a "Type" selection.

I think the most straight-forward solution would be:
- Include a None/Choose Link Type… option in the type dropdown.
  - When this is selected, any other sub-fields should be hidden or disabled

**Comment by sebastian-lenz** [comment]
I'll close this issue due to inactivity. This feature has been implemented for version 2 of this plugin.
