### ISSUE TITLE
Checking if a link is empty returns true always

### ISSUE THREAD

**Issue by mediabeastnz** [sebastian-lenz/craft-linkfield#65]
I think a recent release must have changed how this field empty values.

For example I normally check if a field on an entry is empty by doing
` {% if entry.fieldLink|length %}...`

This worked perfectly but recently it seems even if no link is selected it somehow must have a length.

**Comment by sebastian-lenz** [comment]
Hi! The twig helper `length` checks the string length of the url returned by the link field. Obviously this should work on an empty field. I'm am not aware of any changes we made to this, the `__toString` method which this relies on has not been changed since initial release. What value do you see if you print the link field directly to your template (e.g. `{{ entry.fieldLink }}`)? Maybe there are some spaces in the url field?

**Comment by mediabeastnz** [comment]
It looks like it's returning `NULL` so `|length` obviously wont work. I know I can use `is not empty` instead but just thought I'd post an issue in case other people start running into this issue.

If no changes have been made your end maybe something changed at a Twig level?

**Comment by mateostabio** [comment]
Noticed the same. I can't believe I didn't see this before launching after the recent update!! Empty buttons all over my site!

**Comment by sebastian-lenz** [comment]
Okay, just looked how this `length`filter actually works, here is the relevant code from Twig: https://github.com/twigphp/Twig/blob/2.x/src/Extension/CoreExtension.php#L1235

I've used xDebug to check what actually happens here when evaluating a link field. The code gets trapped in the check for [`Traversable`](https://github.com/twigphp/Twig/blob/2.x/src/Extension/CoreExtension.php#L1249) cause our Link model is (and always has been) a subclass of Yii's model class which implements `Traversable`. When traversed the model class returns an array of all attributes on the model. 

The `length` filter therefore always returns `7` when used with a link field.

So, please do not use the `length` filter to check whether the link has a value. It will not work and it never has worked (if it did it was per accident). We offer the `isEmpty` helper for this exact scenario. Also I would like to warn you to use the `length` check on any other field in Craft as there are multiple fields that will return a model and you'll run into the same issue.

**Comment by sebastian-lenz** [comment]
Just to add an example, the intended way of doing this is the following:
```
{% if not entry.fieldLink.isEmpty %}
  {{ entry.fieldLink.link }}
{% endif %}
```

**Comment by mediabeastnz** [comment]
Thanks for looking into it @sebastian-lenz. I've got some updating to do :)
