### ISSUE TITLE
No Documentation link in Plugins control panel

### ISSUE THREAD

**Issue by marionnewlevant** [sebastian-lenz/craft-linkfield#66]
I think you just need to add 
```
    "documentationUrl": "https://github.com/sebastian-lenz/craft-linkfield/blob/master/README.md"
```
To the `extra` section in composer.json, or 
```
    "docs": "https://github.com/sebastian-lenz/craft-linkfield/blob/master/README.md"
```
to the `support` section, but when I try this after the install, it isn't showing up, so I'm not going to submit a pull request.

**Comment by sebastian-lenz** [comment]
I see both a "Documentation" as well as an "Repository" link within the plugin store, both link to the GitHub page of the plugin. Maybe Craft has changed that behavior meanwhile?
