### ISSUE TITLE
CraftQL error (implementing types for CategoryInterface)

### ISSUE THREAD

**Issue by Tam** [sebastian-lenz/craft-linkfield#67]
I'm getting the following error in CraftQL:

```
Could not find possible implementing types for CategoryInterface in schema. Check that schema.types is defined and is an array of all possible types in the schema.
```

Craft: 3.1.31
Plugin: 1.0.19

**Comment by sebastian-lenz** [comment]
I've just tested Link Field in combination with a categories link type and I don't see no problem there, I can query and receive category data in GraphQL as intended. Could you share some additional details on how to reproduce that issue?

**Comment by sebastian-lenz** [comment]
Brandon Kelly submitted some [fixes](https://github.com/markhuot/craftql/commit/d52ea95e05af376b3beb862c8e264bdb36895af8) to the GraphQL repository related to categories, maybe your category problems are caused by the GraphQL plugin itself?

**Comment by sebastian-lenz** [comment]
We've ditched support for GraphQL as Craft now has native GraphQL support.
