### ISSUE TITLE
Plugin field presets

### ISSUE THREAD

**Issue by jhealey5** [sebastian-lenz/craft-linkfield#69]
Would it be reasonable and possible to have a plugin settings page where we can set a preset/default for the link field? I have a site with many link fields and it's very tedious to have to click the same setup each time. 99% of my fields look like 
![image](https://user-images.githubusercontent.com/1771431/59910361-a081fa00-9409-11e9-8cf2-cb8210ff7d82.png)

And whilst I can get around some using Neo, the vast majority aren't able to be in Neo fields.

Having a plugin settings page where I can preset those settings and then any field added automatically inherits those would be so helpful, and I could override where need be.

Really great plugin, only let down by the tediousness in creating multiple fields.

**Comment by sebastian-lenz** [comment]
Hi, thanks for your suggestion.

This feature request has already been suggested, please see #47.
