### ISSUE TITLE
Doesn't work with multisite

### ISSUE THREAD

**Issue by lenvanessen** [sebastian-lenz/craft-linkfield#7]
On multisite it will always fetch the entries from the main site, making it unusable in the other sites.

**Comment by davidhellmann** [comment]
Hm, that's a problem. Run into it right now. Any plans to update this?

**Comment by sebastian-lenz** [comment]
Just checked it, I compared my code to the one of the default entry field. Seems like the only thing they are doing different is passing the site id of the current element to the input. I've added that to the plugin.

**Comment by lenvanessen** [comment]
They also add a sectio’s to the settings called avanced, Where you can
control the behaviour

Op 23 februari 2018 om 20:49:40, Sebastian Lenz (notifications@github.com)
schreef:

**Comment by lenvanessen** [comment]
@sebastian-lenz this doesn't work. It does allow you to select a entry from the current site, but the twig getUrl now returns null

**Comment by lenvanessen** [comment]
Nevermind, works like a charm.
