### ISSUE TITLE
Getting unresolved alias Urls

### ISSUE THREAD

**Issue by christianLuis** [sebastian-lenz/craft-linkfield#71]
Hello guys,

I'm using 
`element.getUrl()`

and do get a Url like this:
`http://@web/someSlug`

The \@web alias is just written in the url. Is this intended?
What do I do wrong?

integrating with the following didn't work either:
`alias(element.getUrl())`

Many thanks
c

**Comment by sebastian-lenz** [comment]
As far as I am aware aliases must always be located at the start of a string. So you must remove the „http://“ part for it to work.

Am 10.08.2019 um 19:36 schrieb Christian Luis <notifications@github.com<mailto:notifications@github.com>>:


Hello guys,

I'm using
element.getUrl()

and do get a Url like this:
http://@web/someSlug

The @web<https://github.com/web> alias is just written in the url. Is this intended?
What do I do wrong?

integrating with the following didn't work either:
alias(element.getUrl())

Many thanks
c

**Comment by christianLuis** [comment]
But I didn’t choose to get the url like this.
I just refered to an entry.


Am 10.08.2019 um 20:05 schrieb Sebastian Lenz <notifications@github.com<mailto:notifications@github.com>>:


Closed #71<https://github.com/sebastian-lenz/craft-linkfield/issues/71>.

**Comment by sebastian-lenz** [comment]
Ah, okay, sorry. I would suggest to check your entry url settings then, maybe the wrong prefix is set there. Aliases always must be the first thing in a string, as Yii, the underlying Framework of Craft, only supports them there. You must have set some configuration like that somewhere.

**Comment by christianLuis** [comment]
Thanks for your help.

For everyone with similar issues:
Configure Base Url right under: Settings > Websites > Your Website > Base URL
