### ISSUE TITLE
Improvement: Display Null when linkField is empty.

### ISSUE THREAD

**Issue by michtio** [sebastian-lenz/craft-linkfield#72]
Currently when you don't use the LinkField and just leave it as default and you just fire `{{ entry.linkField }}` in your template it will display an ID.

Rather than displaying an ID when the LinkField hasn't been filled in ( no entry / url / asset / ... chosen ) it would be really useful that the field displays `null`. So when you're building more complicated blocks or macros you can do a simple check as in `{{ entry.linkField ? true : false }}`

**Comment by michtio** [comment]
I will close this issue since it was a superTable problem rather than a linkField issue.

**Comment by sebastian-lenz** [comment]
Please keep in mind that the link field always returns an instance of [Link](https://github.com/sebastian-lenz/craft-linkfield/blob/master/src/models/Link.php). If you print that value directly in your templates, the [__toString](https://github.com/sebastian-lenz/craft-linkfield/blob/master/src/models/Link.php#L395) method will be invoked. It either returns an url or nothing, depending on the value set on the field.
