### ISSUE TITLE
Error with Craft 3.3 update

### ISSUE THREAD

**Issue by djurdjen** [sebastian-lenz/craft-linkfield#74]
When selecting the linkfield type in the field editor it gives me the following error message:
`Argument 1 passed to craft\web\View::namespaceInputId() must be of the type string,`

craft-linkfield: 2.0.0-beta.5
craft: 3.3

**Comment by sebastian-lenz** [comment]
Thank you for reporting this!

**Comment by sebastian-lenz** [comment]
There is a new beta release that contains a fix for this issue:
https://github.com/sebastian-lenz/craft-linkfield/releases/tag/2.0.0-beta.6
