### ISSUE TITLE
FR: Turn options on, rather than off

### ISSUE THREAD

**Issue by darylknight** [sebastian-lenz/craft-linkfield#76]
When you create a new field, all the options are on:

![image](https://user-images.githubusercontent.com/1250017/65384753-a5b75380-dd2e-11e9-886d-97c96c2be461.png)

It's a minor thing, but if you've already turned off "Enable all", i think it would be nicer to turn ON the ones you want to use, rather than switching them all off; I nearly always only use "Entry".

**Comment by sebastian-lenz** [comment]
Hi, thanks for the feedback. Yes, the current defaults could be optimized. I've turned on the option "All" by default now, individual link types are now disabled by default.

**Comment by darylknight** [comment]
Nice, thanks!

**Comment by darylknight** [comment]
Are you planning to release this soon? Toggle switches are still all on by default.
