### ISSUE TITLE
URL length is limited to about 140 characters

### ISSUE THREAD

**Issue by ockam** [sebastian-lenz/craft-linkfield#8]
When using URL longer than around 140 characters, I get a validation error stating that the field in longer than 255 characters.

I’m currently on C3 RC11.

**Comment by ockam** [comment]
Just found out that linkfiled store a json object in a `varchar(255)`, which explain its limit and the error.

May I suggest using a `text` field instead.

**Comment by nfourtythree** [comment]
@ockam I have submitted a pull request #9 to get this updated. Hopefully will be merged in soon, if not you can install from my fork

**Comment by ockam** [comment]
@nfourtythree cool! But doesn’t it require a migration to update current install? (I’m a  noob regarding plugins....)

**Comment by nfourtythree** [comment]
@ockam just give it a test and if you go into `settings > fields`, head to your field and just resave the settings, it updates the column type in the DB and from my test kept all the data fine*.

* your mileage may vary and I am not responsible for any data loss! 🔒

**Comment by ockam** [comment]
Thanks.

@sebastian-lenz are you considering accepting pull request #9?
(don’t mean to put pressure on you, just want to know where you’re heading. :) )

**Comment by sebastian-lenz** [comment]
Thanks for the pull request @nfourtythree!

**Comment by nfourtythree** [comment]
No problem @sebastian-lenz, always happy to help!
