### ISSUE TITLE
Missing «target» in graphql

### ISSUE THREAD

**Issue by Jones-S** [sebastian-lenz/craft-linkfield#80]
Hey there

Another issue:
I think the `target` which was available in linkfield 1 and craftql is now missing in graphql.

So the option if the link should open in an new window can't be read out...

<img width="378" alt="image" src="https://user-images.githubusercontent.com/7059580/67202714-913ba900-f409-11e9-8cbf-94c2e0044b83.png">

Thank you for having a look at it.
cheers

Plugin version: `2.0.0-beta.6`
Craft: `v3.4.x-dev`

**Comment by sebastian-lenz** [comment]
Hey @Jones-S, thanks for reporting this. The field is missing in our GraphQL type, I've updates the 2.0 branch to include the definition.

**Comment by Jones-S** [comment]
@sebastian-lenz:
Thanks, it works 👍

**Comment by Jones-S** [comment]
I see. I can't use the packagist version yet, because I believe you have not made any new beta release, is that right?

When do you think will this be available on packagist?
Cheers and thx

**Comment by Jones-S** [comment]
Sorry I think I can use `    "sebastianlenz/linkfield": "2.0.x-dev",` in my composer.

**Comment by bzin** [comment]
@sebastian-lenz migrating it to `2.0.x-dev` form `1.0.20` is indeed not working. It breaks the field when trying to update to use it with the new GraphQL.
