### ISSUE TITLE
Browser validation in HUD

### ISSUE THREAD

**Issue by timkelty** [sebastian-lenz/craft-linkfield#86]
When editing an entry with a Link Field, the brower validation for `type=url` doesn't interfere because the form has a `novalidate` attribute.

When editing in the HUD, the form is missing the `novalidate` attribute, so values that should work that technically aren't URLs according to the browser, wont. E.g. root-relative URLs, URLs with aliases.

**Comment by timkelty** [comment]
Looks like its fixed in Craft!

**Comment by sebastian-lenz** [comment]
Best issue ever. 😉
