### ISSUE TITLE
Feed Me import doesn't allow importing of target

### ISSUE THREAD

**Issue by robmcfadden** [sebastian-lenz/craft-linkfield#88]
I'm assuming this is something on the link field side, but I'm not positive. I was expecting to see Target in the list of options here...

![Screen Shot 2020-01-27 at 9 40 50 AM](https://user-images.githubusercontent.com/435632/73183684-39d46580-40e9-11ea-929f-4189ed7321ab.png)

**Comment by sebastian-lenz** [comment]
Hi @robmcfadden, thank you for your feedback. We currently don't offer any special support for FeedMe. Somebody has to add some advanced support to catch these fields.

**Comment by mightyfineyall** [comment]
Second this - you can import custom link text, but not the actual custom url itself. Had to revert to plain text links for importing large quantities of stores (in this case, a mall directory).

**Comment by sebastian-lenz** [comment]
I've just added native support for FeedMe to v2 of the plugin. The field `target` can now be mapped or set to a default value.
