### ISSUE TITLE
Generated Link Attrubutes render typo "arial-label" rather than "aria-label"

### ISSUE THREAD

**Issue by AimeeMS** [sebastian-lenz/craft-linkfield#91]
By using the various accessors to get the different properties of the link, such as .getLink() or .getLinkAttributes(), I am seeing that "aria-label" is outputted or rendered as "arial-label".

<img width="592" alt="Screen Shot 2020-02-04 at 10 21 25 AM" src="https://user-images.githubusercontent.com/17086680/73764243-37e95280-4738-11ea-98cd-fa16011ee10c.png">
<img width="728" alt="Screen Shot 2020-02-04 at 10 21 51 AM" src="https://user-images.githubusercontent.com/17086680/73764252-3e77ca00-4738-11ea-8c60-7280135d1cd9.png">

**Comment by sebastian-lenz** [comment]
We actually have a merged pull request that fixes that error: https://github.com/sebastian-lenz/craft-linkfield/commit/c086aef3f2d862cdc5288b2446ebbba26ccfe9bf

However, it never got published. I'll give the bug #90 a bit more time to hopefully resolve and then release a new version that will contain the fix. If you need the update early please bump your dependency to `dev-master`.
