### ISSUE TITLE
Please add customQuery to docs

### ISSUE THREAD

**Issue by darylknight** [sebastian-lenz/craft-linkfield#96]
I needed to detect whether there was a custom query appended to the link url so I can use it to scroll down the page if the link is to a section on the same page.
Discovered that entry.button.customQuery is available through {{ dump(entry.button) }} but it's not in the docs. Could you add it please?

**Comment by sebastian-lenz** [comment]
Yeah, you are right, we should improve the documentation, it's pretty spare right now.
