### ISSUE TITLE
Obfuscate emails?

### ISSUE THREAD

**Issue by ursbraem** [sebastian-lenz/craft-linkfield#99]
What is your recommendation if email addresses should be obfuscated?
I switched to craft-linkfield from linkit, where Brad recommended two plugins as an alternative.

https://craftcms.stackexchange.com/questions/33914/linkit-transform-content/33926#33926

Should I run an Obfuscator plugin on top of the linkfield?

**Comment by sebastian-lenz** [comment]
Well, that's what I am doing in my projects. As mail links can originate in all kind of places (redactor fields, templates, link fields, etc) we usually filter the entire rendered html and obusfactor mail links. Here is a script I commonly use:
https://github.com/sebastian-lenz/craft-essentials/blob/master/src/services/MailEncoder.php

The plugin you've linked which exposes a Twig tag also looks like a good alternative. And, just to clarify it, the link field does not contain an obusfactor itself.

**Comment by ursbraem** [comment]
Thanks!!
